dvsa/mes-mobile-app

- src/pages/declaration-consent/declaration-consent.html
- src/pages/declaration-consent/declaration-consent.ts
- src/pages/test-result/test-result.ts
- src/providers/fault-store/fault-store.ts
The enabled state of the continue button is determined by a combination of the insurance/residency checkboxes and the signature. Fixing failure to unset signature in component after clearing signature pad.
> MES-936/932 - Prevent proceeding beyond declaration consent after clearing signature + remove recording consent

- src/components/all-on-one-form-sub-element-hold-no-modal/all-on-one-form-sub-element-hold-no-modal.ts
Jira ticket number MES-1147
Making sure that DE can only record one driving fault against Manoeuvres _Control_ and _Observations_ actions.
Screenshot would not be applicable here.
> MES-1147 Solving the multiple driving fault bug on Manoeuvres 

- src/help/components/components.module.ts
- src/help/components/help-header/help-header.html
- src/help/components/help-header/help-header.scss
- src/help/components/help-header/help-header.ts
- src/help/help.module.ts
This is a quick PR so that both devs in appy tappers can create any custom components needed for the help pages in the help module.
This PR also includes a part completed help-header which is not visible on any pages as of yet
> MES-1054 - Added the ability to put Components in the Help Module

- package-lock.json
- package.json
- src/environment/environment.dev.ts
- src/environment/environment.staging.ts
- src/environment/models/environment.model.ts
- src/pages/journal/journal.html
- src/pages/journal/journal.ts
- src/providers/app-config/__mocks__/app-config.mock.ts
- src/providers/app-config/__mocks__/environment.mock.ts
- src/providers/app-config/app-config.model.ts
- src/providers/app-config/app-config.ts
- src/providers/authentication/__mocks__/authentication.mock.ts
- src/providers/authentication/__mocks__/ms-adal.mock.ts
- src/providers/authentication/__tests__/authentication.spec.ts
- src/providers/authentication/authentication.ts
Pulls in a new package to help decode the JWT from Azure AD allowing us to retrieve `employeeId`. This is pulled into the journal screen and displayed as an example.
As part of the this work, I created 8 different user accounts with different employee Ids which we can use in the [future story](https://jira.i-env.net/browse/MES-1421) to retrieve journal data based on employee id.
The full list of user accounts, credentials and employee ids are available [here](https://wiki.i-env.net/display/MES/Azure+AD+%28dev%29+test+users+and+staff+id%27s). You can add these accounts to your Authenticator app and then switch between them easily when logging into the app -
> MES-1371 mock staff ids

- mock/local-journal.json
- src/app/app.scss
- src/pages/candidate-details/candidate-details.html
- src/pages/component-library/component-library.html
- src/pages/component-library/components/typography/typography.html
- src/pages/journal/components/activity-slot/activity-slot.html
- src/pages/journal/components/candidate-link/__tests__/candidate-link.spec.ts
- src/pages/journal/components/candidate-link/candidate-link.html
- src/pages/journal/components/time/__tests__/time.spec.ts
- src/pages/journal/components/time/time.html
- src/pages/journal/components/time/time.scss
- src/pages/login/login.html
- src/theme/sass-partials/_reset.scss
- src/theme/sass-partials/_typography.scss
Implementing typography in the component library. Also cleaning up the application where these changes apply.
We are using Roboto font-family for the time being. Because San Francisco font is restricted only for iOS devices. So we need to find out how the licensing applies here before we start using it.
This is a weekly activity what we are doing with Oli - next week we are planning to take a look at the colour palette and implement the correct design for a card. Also will extend the component library page so that it has more information about the different components (when to use it, how to use it etc.)
> Component library typography improvements

- src/common/__tests__/date-time.spec.ts
- src/common/date-time.ts
- src/pages/journal/__tests__/journal.reducer.spec.ts
- src/pages/journal/journal.reducer.ts
Add a method to calculate difference between dates; ensure selected day is always today or greater
> Ensure selected journal day can't be before today

- mock/local-journal.json
- src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
- src/pages/journal/components/test-slot/test-slot.ts
* Journal poller (MES-1477) puts `null` into `specialNeeds` as we can't store blank string in DynamoDB.
* Guard against this property being null.
> Guard against the special needs text being null

- src/pages/candidate-details/__tests__/candidate-details.selector.spec.ts
- src/pages/candidate-details/candidate-details.selector.ts
- test/e2e/features/02-journal.feature
After discussing with the POs they would prefer having Single Slot instead of Double Slot so this PR is introducing that change.
> Mes 1834 double slot changed to single slot

- src/pages/journal/components/activity-slot/__tests__/activity-slot.spec.ts
- src/pages/journal/components/activity-slot/activity-slot.html
- src/pages/journal/components/empty-slot/__tests__/empty-slot.spec.ts
- src/pages/journal/components/empty-slot/empty-slot.html
Add location element to display before empty slots and activity slots
> Mes 1829 location not always displayed before slot

- src/pages/login/__tests__/login.spec.ts
- src/pages/login/login.html
- src/pages/login/login.ts
- src/providers/app-config/app-config.constants.ts
- src/providers/app-config/app-config.ts
- src/providers/authentication/authentication.constants.ts
Show a not authorised page when the user is not allowed to access the app (doesn't exist in the users table in dynamoDB)
> Mes 1777 display not authorised message

- src/providers/hammer/__tests__/hammer.spec.ts
Simple tests where hammer events are directly invoked to ensure that configured callbacks are called as expected.
This is a workaround for not being able to make emulated press+hold events trigger the callbacks as originally intended.
> MES-76: Add unit test for hammer wrappers invoking provided callbacks (MES-1951)

- mock/local-journal.json
- src/modules/tests/__tests__/tests.selector.spec.ts
- src/modules/tests/test_data/test-data.selector.ts
- src/modules/tests/tests.reducer.ts
- src/modules/tests/tests.selector.ts
- src/pages/test-report/__tests__/test-report.spec.ts
- src/pages/test-report/components/competency/competency.ts
- src/pages/test-report/components/driving-fault-summary/__tests__/driving-fault-summay.spec.ts
- src/pages/test-report/components/driving-fault-summary/driving-fault-summary.html
- src/pages/test-report/components/driving-fault-summary/driving-fault-summary.scss
- src/pages/test-report/components/driving-fault-summary/driving-fault-summary.ts
- src/pages/test-report/test-report.html
- src/pages/test-report/test-report.module.ts
- src/pages/test-report/test-report.scss
- src/pages/test-report/test-report.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.ts
- src/pages/waiting-room/waiting-room.ts
Implementing a component which displays the summary of driving faults recorded against certain competencies (not all just yet, for example driving faults on Manoeuvres has to be included later on)
> Implementing driving fault summary

- mock/local-journal.json
* Journal effects tests were expecting slots tomorrow, but a 1 day gap had appeared between the slots
* Remove this gap to fix the tests
> Fix failing journal effects tests by changing 2-day date differential to 1 day

- src/modules/tests/pass-completion/__tests__/pass-completion.reducer.spec.ts
- src/modules/tests/pass-completion/__tests__/pass-completion.selector.spec.ts
- src/modules/tests/pass-completion/pass-completion.actions.ts
- src/modules/tests/pass-completion/pass-completion.reducer.ts
- src/modules/tests/pass-completion/pass-completion.selector.ts
- src/pages/pass-finalisation/pass-finalisation.html
- src/pages/pass-finalisation/pass-finalisation.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.ts
- src/pages/waiting-room/waiting-room.ts
- Updated pass completion reducer and selector, created tests
- Added radio buttons to record whether provisional license has been provided
- Radio buttons are unselected initially to allow validation in future story (MES-1922)
- Value of radio buttons is set from store on page init
**There's possibly a better way to set the value of radio buttons on page init. Maybe using `RadioControlValueAccessor`? Would appreciate another pair of eye on my approach.**
> MES 1096 - add provisional license check radio buttons on debrief

- src/pages/test-report/__tests__/test-report.reducer.spec.ts
- src/pages/test-report/__tests__/test-report.selector.spec.ts
- src/pages/test-report/__tests__/test-report.spec.ts
- src/pages/test-report/components/dangerous-tooltip/__tests__/dangerous-tooltip.spec.ts
- src/pages/test-report/components/dangerous-tooltip/dangerous-tooltip.html
- src/pages/test-report/components/dangerous-tooltip/dangerous-tooltip.scss
- src/pages/test-report/components/dangerous-tooltip/dangerous-tooltip.ts
- src/pages/test-report/components/toolbar/__tests__/toolbar.spec.ts
- src/pages/test-report/components/toolbar/toolbar.html
- src/pages/test-report/components/toolbar/toolbar.scss
- src/pages/test-report/components/toolbar/toolbar.ts
- src/pages/test-report/test-report.actions.ts
- src/pages/test-report/test-report.html
- src/pages/test-report/test-report.module.ts
- src/pages/test-report/test-report.reducer.ts
- src/pages/test-report/test-report.scss
- src/pages/test-report/test-report.selector.ts
- src/pages/test-report/test-report.ts
Add's a dangerous fault mode to the test report page. 
This does not allow you to mark dangerous faults.
> MES-1923 - Dangerous Fault Mode

- src/app/app.module.ts
- src/app/app.scss
- src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.spec.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.html
- src/pages/waiting-room-to-car/waiting-room-to-car.scss
- src/pages/waiting-room-to-car/waiting-room-to-car.ts
- src/providers/question/__mocks__/question.mock.ts
- src/providers/question/question.ts
- src/providers/question/tell-me-question.constants.ts
- src/providers/question/tell-me-question.model.ts
- src/theme/sass-partials/_alert.scss
- src/theme/sass-partials/_input.scss
- src/theme/variables.scss
* Use reference data for Tell Me questions as defined on Confluence and expose through new QuestionProvider
* Add `ion-select` to allow selection of a Tell Me question
* Restyle `ion-alert` to fit with the Tell Me dialog designs (please forgive me...)
> MES-2020: Populate show me question selector (MES-1907)

- src/pages/pass-finalisation/pass-finalisation.html
- src/pages/pass-finalisation/pass-finalisation.scss
- src/pages/waiting-room-to-car/waiting-room-to-car.html
- src/pages/waiting-room-to-car/waiting-room-to-car.scss
- src/theme/sass-partials/_row.scss
This refactor simplifies and consolidates how the validation is applied to the Waiting Room to Car page and the Debrief 2 page (Pass Finalisation).
- removed unnecessary rows and columns from layout
- created two new classes for row elements: `mes-component-row` and `mes-validated-row`
- the validation bar style is now used from the global validation style.
- component row has a psuedo element to ensure it aligns with the validated rows
Possible future work to create reusable row components for:
- input
- radio
- checkbox
> Refactor form validation layout and styling

- src/modules/tests/test_data/__tests__/test-data.selector.spec.ts
- src/modules/tests/test_data/test-data.selector.ts
- src/pages/debrief/__tests__/debrief.spec.ts
- src/pages/debrief/debrief.html
- src/pages/debrief/debrief.ts
Displaying the ETA faults in the debrief page
https://jira.i-env.net/browse/MES-2038
> Mes-2038 - show eta in debrief

- src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
- src/modules/tests/test_data/__tests__/test-data.selector.spec.ts
- src/modules/tests/test_data/test-data.actions.ts
- src/modules/tests/test_data/test-data.reducer.ts
- src/modules/tests/test_data/test-data.selector.ts
- src/pages/debrief/__tests__/debrief.spec.ts
- src/pages/debrief/debrief.html
- src/pages/debrief/debrief.ts
- src/pages/test-report/test-report.html
- src/pages/test-report/test-report.ts
Added the ECO faults to the debrief summary, also ended up creating the button on test report page to toggle the ECO faults.
https://jira.i-env.net/browse/MES-2039
> MES-2039 - Added eco buttons to test report and debrief

- mock/local-journal.json
- src/modules/tests/__tests__/tests.reducer.spec.ts
- src/modules/tests/__tests__/tests.selector.spec.ts
- src/modules/tests/test-status/__tests__/test-status.reducer.spec.ts
- src/modules/tests/test-status/test-status.actions.ts
- src/modules/tests/test-status/test-status.model.ts
- src/modules/tests/test-status/test-status.reducer.ts
- src/modules/tests/tests.reducer.ts
- src/pages/debrief/__tests__/debrief.spec.ts
- src/pages/test-report/__tests__/test-report.spec.ts
- src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.spec.ts
- src/pages/waiting-room/__tests__/waiting-room.spec.ts
- src/pages/waiting-room/waiting-room.ts
* Add a new key in the store under `tests` to store `testLifecycles`
* Keep this state tracking distinct from captured test data model (`startedTests`) to ensure it's not submitted to the backend
* Ensure that tests from from `NotStarted` to `Started` when Waiting Room form is submitted
**State tree**
```
tests: {
currentTest: {
slotId: '1005'
},
startedTests: {
'1005': {
...
}
},
testLifecycles: {
'1005': 'Started'
}
}
```
> MES-2047: Setup test lifecycle, moving to started once progressing beyond Waiting Room (MES-2028)

- src/app/app.module.ts
- src/pages/test-report/__tests__/test-report.spec.ts
- src/pages/test-report/test-report.module.ts
- src/pages/test-report/test-report.ts
- src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.spec.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.module.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.ts
- src/pages/waiting-room/__tests__/waiting-room.spec.ts
- src/pages/waiting-room/waiting-room.ts
This PR activates the Single App Mode , Screen Orientation and Insomina plugins on the Waiting Room page and disabled them when leaving the Test Report Page.
This is instead of enabling and disabling on every page in the journey between those 2 points which were causing some strange behaviours.
> Plugin Activation Refactor

- src/modules/tests/__tests__/tests.selector.spec.ts
- src/modules/tests/tests.selector.ts
- src/pages/journal/components/test-outcome/__tests__/test-outcome.spec.ts
- src/pages/journal/components/test-outcome/test-outcome.html
- src/pages/journal/components/test-outcome/test-outcome.scss
- src/pages/journal/components/test-outcome/test-outcome.ts
- src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
- src/pages/journal/components/test-slot/test-slot.html
- src/pages/journal/components/test-slot/test-slot.ts
- src/pages/journal/journal.ts
- src/providers/slot/slot.ts
- src/theme/sass-partials/_buttons.scss
* Select the state of the test into TestSlotComponent component state
* Refactor predicate for showing start test button to use test status
> MES-2076: Show a finalise test button on slots where the test is decided (MES-2028)

- src/pages/back-to-office/__tests__/back-to-office.spec.ts
- src/pages/back-to-office/back-to-office.ts
- src/pages/test-report/__tests__/test-report.spec.ts
- src/pages/test-report/test-report.ts
Link to story - https://jira.i-env.net/browse/MES-2071
After a discussion with Steve Holmes and Graham OBrien we'll be moving the "turning off" of ASAM, screen orientation lock and insomnia from the exiting "TestReportPage" to entering of the "BackToOfficePage".
> MES-2701 - Moves unlocking of device from exit of TestReportPage to BackToOfficePage

- mock/local-journal.json
- src/pages/office/__tests__/office.spec.ts
- src/pages/office/office.html
- src/pages/office/office.scss
- src/pages/office/office.ts
Added ETA fault display to office page, 
https://jira.i-env.net/browse/MES-2048
Also added ECO faults display (MES-2049) while waiting on initial office form creation,
https://jira.i-env.net/browse/MES-2049
> MES-2048 - show eta on office page

- src/environment/models/environment.model.ts
- src/providers/app-config/__mocks__/app-config.mock.ts
- src/providers/app-config/app-config.model.ts
- src/providers/app-config/app-config.ts
- src/providers/authentication/__tests__/authentication.spec.ts
- src/providers/authentication/authentication.ts
- src/providers/data-store/__mocks__/data-store.mock.ts
- src/providers/test-persistence/__mocks__/test-persistence.mock.ts
- src/providers/test-persistence/__tests__/test-persistence.spec.ts
- src/providers/test-persistence/test-persistence.ts
* Given that we only have one test that can be started in the dev test data, once we implement restoration of persisted test state and the test has been completed, the only way to re-run the test is to clear the persistent store
* Add a feature flag for clearing the persisted tests on logout
* To run a test again, set `logoutClearsTestPersistence` to true, logout and kill the app
> MES-2110: Clear test persistence when logging out on dev config (MES-2036)

- src/pages/test-report/components/competency/__tests__/competency.spec.ts
- src/pages/test-report/components/competency/competency.html
- src/pages/test-report/components/competency/competency.ts
Quick PR to reinstate the ability to remove faults by tapping, not just by long pressing (removed in MES-2073)
> Reinstate remove fault on tap gesture

- src/pages/office/office.html
- src/pages/office/office.scss
- src/pages/office/office.ts
* Previously, there was no text indicator on the validation, it now says "Select weather conditions".
* Previously, the validation indicator at the very beginning of the row wasn't showing.
* When selecting a lot of weather conditions, the row reflowed. This doesn't happen anymore.
> MES-1102 fixes: Add missing weather condition validation indicators and fix select reflow

- src/modules/tests/test_data/test-data.actions.ts
- src/modules/tests/test_data/test-data.reducer.ts
- src/pages/test-report/components/controlled-stop/__tests__/controlled-stop.spec.ts
- src/pages/test-report/components/controlled-stop/controlled-stop.html
- src/pages/test-report/components/controlled-stop/controlled-stop.scss
- src/pages/test-report/components/controlled-stop/controlled-stop.ts
- src/shared/constants/competencies/catb-competencies.ts
Allow faults to be recorded against the controlled stop and display them in the competency button.
This is a copy of the regular competency button but with customised logic and styling to ensure that only one type of fault can be recorded (either a driving fault, a serious fault or a dangerous fault) and displayed as a badge in the reduced width button.
The tick box is checked when a fault is recorded. It can only be unchecked if there are no faults.
The same div-as-button code, ripple effect and activated state are used, just like the regular competency component.
There's probably scope for a future refactor to move some of this code into a shared custom `mes-button` component.
> MES-1849 mark faults against controlled stop

- src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
- src/modules/tests/test_data/test-data.actions.ts
- src/modules/tests/test_data/test-data.constants.ts
- src/modules/tests/test_data/test-data.reducer.ts
- src/pages/test-report/components/competency/__tests__/competency.spec.ts
- src/pages/test-report/components/competency/competency.ts
- src/pages/test-report/components/controlled-stop/__tests__/controlled-stop.spec.ts
- src/pages/test-report/components/controlled-stop/controlled-stop.ts
- src/pages/test-report/components/manoeuvre-competency/__tests__/manoeuvre-competency.spec.ts
- src/pages/test-report/components/manoeuvre-competency/manoeuvre-competency.ts
This PR:
- Extracts the manoeuvre competencies from Competencies enum to ManoeuvreComptencies enum
- Removes the attribute from the drivingFault, seriousFault or dangerousFault array when it is 0 or false
- Commented out a load of code which incorrectly implements Controlled Stop
> MES-2127 - Remove Attribute from Store when no fault exists

- src/modules/tests/candidate/__tests__/candidate-selector.spec.ts
- src/modules/tests/candidate/candidate.selector.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.html
- src/pages/waiting-room-to-car/waiting-room-to-car.ts
fix for eyesight bug.
https://jira.i-env.net/browse/MES-2066
This is a temporary fix to bind the form validation with the store.
> MES-2066 added temporary fix for eyesight validation bug

- src/pages/test-report/__tests__/test-report.spec.ts
- src/pages/test-report/components/competency-button/__tests__/competency-button.spec.ts
- src/pages/test-report/components/competency-button/competency-button.html
- src/pages/test-report/components/competency-button/competency-button.scss
- src/pages/test-report/components/competency-button/competency-button.ts
- src/pages/test-report/components/competency/__tests__/competency.spec.ts
- src/pages/test-report/components/competency/competency.html
- src/pages/test-report/components/competency/competency.scss
- src/pages/test-report/components/competency/competency.ts
- src/pages/test-report/components/controlled-stop/__tests__/controlled-stop.spec.ts
- src/pages/test-report/components/controlled-stop/controlled-stop.html
- src/pages/test-report/components/controlled-stop/controlled-stop.scss
- src/pages/test-report/components/controlled-stop/controlled-stop.ts
- src/pages/test-report/components/examiner-takes-action/__tests__/eta.spec.ts
- src/pages/test-report/components/examiner-takes-action/eta.html
- src/pages/test-report/components/examiner-takes-action/eta.scss
- src/pages/test-report/components/examiner-takes-action/eta.ts
- src/pages/test-report/components/legal-requirement/__tests__/legal-requirement.spec.ts
- src/pages/test-report/components/legal-requirement/legal-requirement.html
- src/pages/test-report/components/legal-requirement/legal-requirement.scss
- src/pages/test-report/components/legal-requirement/legal-requirement.ts
- src/pages/test-report/components/test-report-components.module.ts
- src/pages/test-report/test-report.html
- src/pages/test-report/test-report.scss
This refactor moves touch interactions, feedback and ripple animation into a new `competency-button` that is then reused in test report components: Competency, Legal Requirements, ETA, Manoeuvres, Controlled Stop.
The button accepts a `[ripple]` input that controls whether the button will ripple on press events. For competencies a `canButtonRipple` function is used to determine if the button will ripple.
I also made a small change to standardise the layout of the buttons on the test report page, removing the need to specify a button width.
> Refactor competency button components

- mock/local-journal.json
- src/pages/journal/components/test-outcome/test-outcome.html
- src/pages/office/__tests__/office.spec.ts
- src/pages/office/components/route-number/route-number.html
- src/pages/office/components/route-number/route-number.ts
- src/pages/office/office.html
- src/pages/office/office.module.ts
- src/pages/office/office.ts
* Enable navigation back to Office page to finalise the write up
* Extract route number capture into a dedicated presentational component
* Have `RouteNumberComponent` handle it's form validation and repopulation of the form value
* Emit an event back to the Office page when the route number changes to update the store
> MES-2153: Repopulate route number when returning to office write up (MES-1129)

- src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
- src/modules/tests/test_data/test-data.reducer.ts
- src/pages/test-report/components/manoeuvres-popover/__tests__/manoeuvres-popover.spec.ts
- src/pages/test-report/components/manoeuvres-popover/manoeuvres-popover.html
- src/pages/test-report/components/manoeuvres-popover/manoeuvres-popover.scss
- src/pages/test-report/components/manoeuvres-popover/manoeuvres-popover.ts
- test-config/karma.conf.js
Ensures that faults can only be added to one manoeuvre by implementing the following disabling logic:
- When a fault is added to a given manoeuvre, we disable the remaining manoeuvres (greyed out and unresponsive).
- Only when all faults have been removed from the given manoeuvre will the remaining manoeuvres be re-enabled.
**Screenshot**:
> Mes 2125 disable unselected manoeuvres

- src/pages/journal/components/test-outcome/test-outcome.html
- src/pages/office/__tests__/office.spec.ts
- src/pages/office/components/candidate-description/candidate-description.html
- src/pages/office/components/candidate-description/candidate-description.ts
- src/pages/office/office.html
- src/pages/office/office.module.ts
- src/pages/office/office.ts
* Extract candidate description capture into a dedicated presentational component
* Have `CandidateDescriptionComponent` handle it's form validation and repopulation of the form value
* Emit an event back to the Office page when the candidate description changes to update the store
> MES-2154: Extract candidate description capture into presentational component handling form repopulation (MES-1129)

- mock/local-journal.json
- src/modules/tests/test-summary/test-summary.selector.ts
- src/pages/office/__tests__/office.spec.ts
- src/pages/office/components/debrief-witnessed/debrief-witnessed.html
- src/pages/office/components/debrief-witnessed/debrief-witnessed.ts
- src/pages/office/office.html
- src/pages/office/office.module.ts
- src/pages/office/office.ts
* Extract debrief witnessed capture into a dedicated presentational component
* Have `DebriefWitnessed` handle it's form validation and repopulation of the form value
* Emit an event back to the Office page when the debrief witnessed status changes to update the store
> MES-2156: Extract debrief witnessed presentational component to handle form repopulation (MES-1129)

- src/pages/office/__tests__/office.spec.ts
- src/pages/office/office.html
- src/pages/office/office.module.ts
- src/pages/office/office.ts
- src/pages/office/show-me-question/show-me-question.html
- src/pages/office/show-me-question/show-me-question.ts
* Extract Show Me question capture into a dedicated presentational component
* Have `ShowMeQuestionComponent` handle it's form validation and repopulation of the form value
* Emit an event back to the Office page when identification changes to update the store
> MES-2158: Extract Show Me Question presentational component to handle form repopulation (MES-1129)

- src/modules/tests/test-summary/test-summary.selector.ts
- src/pages/office/__tests__/office.spec.ts
- src/pages/office/components/d255/d255.html
- src/pages/office/components/d255/d255.ts
- src/pages/office/office.html
- src/pages/office/office.module.ts
- src/pages/office/office.ts
* Extract D255 capture into a dedicated presentational component
* Have `D255Component` handle it's form validation and repopulation of the form value
* Emit an event back to the Office page when D255 changes to update the store
> MES-2160: Extract D255 presentational component to handle form repopulation (MES-1129)

- src/modules/tests/test-summary/test-summary.actions.ts
- src/modules/tests/test-summary/test-summary.selector.ts
- src/pages/debrief/debrief.selector.ts
- src/pages/office/__tests__/office.spec.ts
- src/pages/office/components/identification/identification.html
- src/pages/office/components/identification/identification.ts
- src/pages/office/office.html
- src/pages/office/office.module.ts
- src/pages/office/office.ts
* **FYI Depends on https://github.com/dvsa/mes-api-definitions/pull/18 and requires a test schema dependency update once merged** ✅ 
* Extract identification capture into a dedicated presentational component
* Have `IdentificationComponent` handle it's form validation and repopulation of the form value
* Emit an event back to the Office page when identification changes to update the store
> MES-2156: Extract identification presentational component to handle form repopulation (MES-1129)

- src/modules/tests/test-summary/test-summary.selector.ts
- src/pages/office/__tests__/office.spec.ts
- src/pages/office/components/independent-driving/independent-driving.html
- src/pages/office/components/independent-driving/independent-driving.ts
- src/pages/office/office.html
- src/pages/office/office.module.ts
- src/pages/office/office.ts
* Extract independent driving capture into a dedicated presentational component
* Have `IndependentDrivingComponent` handle it's form validation and repopulation of the form value
* Emit an event back to the Office page when independent driving changes to update the store
* Remove unnecessary subscriptions as suggested by @szabolcs-keresztes.
* Remove last of `FormGroup` setup from the Office page component, it's all now handled by subcomponents.
> MES-2154: Extract independent driving presentational component to handle form repopulation (MES-1129)

- src/modules/tests/test_data/test-data.selector.ts
- src/pages/debrief/__tests__/debrief.selector.spec.ts
- src/pages/debrief/debrief.selector.ts
- src/pages/debrief/debrief.ts
- src/pages/test-report/components/manoeuvre-competency/manoeuvre-competency.constants.ts
- tslint.json
- Include the manoeuvre faults in the counts on the summary screen
- Show the manoeuvre fault descriptions in the relevant sections
- **Update linting rule so arguments don't need to be aligned**
> MES-2131 persist manoeuvre faults to summary screen

- src/modules/tests/test_data/test-data.actions.ts
- src/modules/tests/test_data/test-data.reducer.ts
- src/pages/test-report/components/manoeuvre-competency/__tests__/manoeuvre-competency.spec.ts
- src/pages/test-report/components/manoeuvre-competency/manoeuvre-competency.ts
- src/pages/test-report/components/manoeuvres-popover/__tests__/manoeuvres-popover.spec.ts
- src/pages/test-report/components/manoeuvres-popover/manoeuvres-popover.ts
- Replicates the logic from `competency.ts` to handle removal of faults from manoeuvure competencies.
- Fixes a bug where the manoeuvres weren't being disabled if you added either Serious or Dangerous faults.
> Mes-2029 - Remove faults manoeuvre

- src/pages/debrief/debrief.html
Fixes bug introduced in #344 where Debrief template wasn't updated to match the new fault/comment model.
> Fix display of driving faults on debrief page

- src/pages/office/__tests__/office.spec.ts
- src/pages/office/office.html
* Fixes references to the comment model that weren't updated in the Office template as part of #344
* Similar fix to #347
> Fix driving fault counts not showing in the Office page

- src/modules/tests/tests.reducer.ts
- src/pages/journal/components/test-outcome/__tests__/test-outcome.spec.ts
- src/pages/journal/components/test-outcome/test-outcome.html
- src/pages/journal/components/test-outcome/test-outcome.ts
- src/pages/journal/journal.actions.ts
* Currently, clicking "Write-up" views the Office form for the latest started test
* Ensure that re-nav from Journal to Office assigns the resumed test slot ID into `/tests/currentTest`
> Allow switching between different writeups

- src/components/end-test-link/end-test-link.scss
- src/components/end-test-link/end-test-link.ts
- src/components/terminate-test-modal/terminate-test-modal.html
- src/components/terminate-test-modal/terminate-test-modal.scss
- Update the terminate test (before test started) modal so that it reuses the shared modal styles created in MES-2170
> MES-2250 update terminate modal to use shared styles

- src/modules/tests/__tests__/tests.reducer.spec.ts
- src/pages/office/components/fault-comment-card/__tests__/fault-comment-card.spec.ts
- src/pages/office/components/fault-comment-card/fault-comment-card.scss
- src/pages/office/components/fault-comment/__tests__/fault-comment.spec.ts
- src/pages/office/components/fault-comment/fault-comment.html
- src/pages/office/components/fault-comment/fault-comment.ts
* Fix issue with some fault comment text areas being severely misaligned
* Fix driving fault counts not displaying next to driving fault comment boxes
* Add a missing unit test from #362
* Unit tests around `FaultCommentComponent` and `FaultCommentCardComponent`
> MES-2245: Office comment alignment + other fixes

- mock/local-journal.json
- src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.spec.ts
- src/pages/waiting-room-to-car/components/eyesight-failure-confirmation/__tests__/eyesight-failure-confirmation.spec.ts
- src/pages/waiting-room-to-car/components/eyesight-failure-confirmation/eyesight-failure-confirmation.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.ts
* Assign the relevant activity code to the test when an eyesight failure is confirmed
* Remove the existing mechanism of indicating a failure to the debrief page with nav params
* Move WRTC persistence to navigation as opposed to form submit to persist on eyesight failure
> MES-2055: Set the activity code to 3 on eyesight failure

- src/pages/office/components/show-me-question/show-me-question.html
- src/pages/office/components/weather-conditions/weather-conditions.html
- src/pages/waiting-room-to-car/waiting-room-to-car.html
- src/theme/sass-partials/_alert.scss
The header and message was being hidden on simple alert prompts - this refactor addresses that by adding a class so the styling can be added more specifically. Now we will be able to use alerts when required.
The screenshots below simply show that the styling hasn't changed.
- Change the three `ion-select` references to include a CSS class so that they can be targeted specifically
- Update the CSS for `_alert.scss` to target the new class
> MES-2270 refactor alert styling to only target select/radio modals

- src/pages/login/__tests__/login.spec.ts
- src/pages/login/login.ts
The login screen does a lot of work to initialise the app (config, auth, persistent storage, analytics etc.). This means that there can be a significant wait for the user whilst they are logging in and before they reach the Journal screen.
This PR adds a loading spinner with a message 'App initialising...' to the login screen which keeps it distinct from the journal spinner. This may come in handy when debugging app startup problems later on.
**Screenshot**
> Adds spinner to app initialisation on login page

- mock/local-journal.json
- src/components/candidate-section/candidate-section.html
- src/components/candidate-section/candidate-section.scss
- src/components/candidate-section/candidate-section.ts
- src/components/components.module.ts
- src/pages/communication-page/__tests__/communication.spec.ts
- src/pages/communication-page/communication.actions.ts
- src/pages/communication-page/communication.html
- src/pages/communication-page/communication.module.ts
- src/pages/communication-page/communication.scss
- src/pages/communication-page/communication.ts
- src/pages/journal/components/test-outcome/__tests__/test-outcome.spec.ts
- src/pages/journal/components/test-outcome/test-outcome.ts
- src/pages/waiting-room/__tests__/waiting-room.spec.ts
- src/pages/waiting-room/waiting-room.html
- src/pages/waiting-room/waiting-room.ts
- Created candidate section component to be shared across Communication and Waiting Room pages. 
- Emits an event for the continue click to allow each page TS to independently handle their onSubmit().
- Implementation of the Communication page view and TS file.
- Removed call for device authentication from back click on Waiting Room page.
- Implemented call for device authentication for back click on Communication page.
> mes-2267: Adding basic communication page layout

- src/modules/tests/test-data/__tests__/test-data.selector.spec.ts
- src/modules/tests/test-data/test-data.selector.ts
- src/providers/test-result/test-result.ts
Szabi and I spotted a bug in how the test result was calculated. Previously it used selectors that were specific to the Debrief page. This meant that if the selectors were changed to make the debrief page behave differently it could affect the test result (not good).
This PR addresses that:
- create a new selector to return count of dangerous faults
- create a new selector to return count of serious faults
- update the test results component to use the new selectors
> Update how the test result is calculated

- src/modules/tests/__mocks__/tests.mock.ts
- src/modules/tests/__tests__/tests.effects.spec.ts
- src/modules/tests/__tests__/tests.reducer.spec.ts
- src/modules/tests/__tests__/tests.selector.spec.ts
- src/modules/tests/tests.actions.ts
- src/modules/tests/tests.reducer.ts
- src/modules/tests/tests.selector.ts
- src/pages/debrief/__tests__/debrief.spec.ts
- src/pages/debrief/debrief.ts
- src/pages/journal/components/practice-card/practice-card.ts
To be able to end practice mode we need to know if we're conducting a practice test. My first iteration of this had a property called `isPracticeMode` stored on the state, but after discussions I decided that this wasn't the best as it was separate from `currentTest`, `startedTest` and `testLifecycles` and so there was the worry that it could become detached / different.
This version uses the slot ID to determine if the test is a practice test. The slot ID is prefixed with `practice_` and a selector can then be used to determine what sort of test this is.
Would welcome any thoughts on this.
> MES-2297 end practice mode

- src/modules/tests/__tests__/tests.reducer.spec.ts
- src/modules/tests/tests.actions.ts
- src/modules/tests/tests.reducer.ts
- src/pages/debrief/debrief.ts
- src/pages/test-report/__tests__/test-report.effects.spec.ts
- src/pages/test-report/test-report.effects.ts
- reset the state of the practice test when it is started
The state is reset by removing the practice test from the state and creating a new test state via createStateObject.
> MES-2319 clear practice test state

- src/pages/waiting-room-to-car/components/tell-me-question/tell-me-question.html
As part of the refactor, the select modal lost it's class.
Before
After
> Bugfix - add class to make tell me select modal correct height

- package-lock.json
- package.json
- src/modules/tests/tests.reducer.ts
- Upgrades Typescript to version 2.8 
- Fixes the required types issue in the tests reducer
Thanks to @ammarhaiderbjss  for finding a solution.
> MES-2336 - Typescript upgrade & Fix for Tests Reducer

- test/e2e/features/02-journal.feature
- test/e2e/step-definitions/journal-steps.ts
Adding in a test for non-test activities into the journal scenarios as a result of finding https://jira.i-env.net/browse/MES-2372.
Note: Since https://jira.i-env.net/browse/MES-2372 has not been delivered yet a couple lines have been commented out. These should be uncommented as part of the ticket.
> Adding non-test activity journal UI test

- src/pages/office/components/d255/d255.ts
Fix bug introduced by refactoring - where selecting the D255 No radio button on the office page caused the field to be considered invalid.
> fix bug with d255 no radio button causing validation error

- mock/local-journal.json
- src/assets/i18n/cy.json
- src/assets/i18n/en.json
- src/pages/debrief/components/debrief-components.module.ts
- src/pages/debrief/components/vehicle-checks-card/__tests__/vehicle-checks-card.selector.spec.ts
- src/pages/debrief/components/vehicle-checks-card/__tests__/vehicle-checks-card.spec.ts
- src/pages/debrief/components/vehicle-checks-card/vehicle-checks-card.html
- src/pages/debrief/components/vehicle-checks-card/vehicle-checks-card.selector.ts
- src/pages/debrief/components/vehicle-checks-card/vehicle-checks-card.ts
* Change selectors of show/tell me question selectors to provide untranslated competency outcomes
* Handle translation to the current language set by the parent page in the `VehicleChecksCardComponent` with async pipe
> i18n for debrief tell me question fault indicators

- src/pages/communication-page/__tests__/communication.spec.ts
- src/pages/communication-page/communication.html
- src/pages/communication-page/communication.scss
- src/pages/communication-page/communication.ts
- src/pages/communication-page/components/new-email/__tests__/new-email.spec.ts
- src/pages/communication-page/components/new-email/new-email.html
- src/pages/communication-page/components/new-email/new-email.ts
- src/pages/communication-page/components/postal-address/postal-address.html
- src/pages/communication-page/components/postal-address/postal-address.scss
- src/pages/communication-page/components/provided-email/__tests__/provided-email.spec.ts
- src/pages/communication-page/components/provided-email/provided-email.html
- src/pages/communication-page/components/provided-email/provided-email.ts
- created function `shouldPreselectADefaultValue()` to determine if default radio selections are required.
- dispatching support centre action from `communication-preferences.actions`.
- enforce the use of component constants as opposed to magic strings
- created function `conditionalDispatchCandidateChoseNewEmail` to conditionally decide if new email radio button should dispatch an action
> mes-1774: Fixing rehydration bug

- mock/local-journal-non-test-activities.json
- mock/local-journal.json
- src/pages/journal/__tests__/journal.effects.spec.ts
- src/pages/journal/journal.effects.ts
- src/providers/journal/__mocks__/journal.mock.ts
- src/providers/journal/journal.ts
* Journal service returns HTTP 304 when there are no changes as per https://github.com/dvsa/mes-journal-service/pull/28.
* Handle this gracefully by using the journal slots already cached on the device.
* Simplify how the `If-Modified-Since` header on the journal request is generated.
> MES-1882: Handle HTTP 304 when fetching journals

- mock/local-journal-non-test-activities.json
- mock/local-journal.json
- src/pages/journal/__tests__/journal.reducer.spec.ts
- src/pages/journal/journal.reducer.ts
* Fixing an issue introduced by #449 
* The `lastRefreshed` was maintained in the state even after logout
* This means that we would get HTTP 304 for journals on the new user without having any journal slots cached
* Reset the entire journal state when unloading, including `lastRefreshed`.
> MES-1882: Ensure we can retrieve journals when logging in as a different user

- src/pages/back-to-office/__tests__/back-to-office.spec.ts
- src/pages/back-to-office/back-to-office.ts
- src/pages/communication-page/__tests__/communication.spec.ts
- src/pages/communication-page/communication.ts
- src/pages/communication-page/components/postal-address/__tests__/postal-address.spec.ts
- src/pages/debrief/__tests__/debrief.spec.ts
- src/pages/health-declaration/__tests__/health-declaration.spec.ts
- src/pages/health-declaration/health-declaration.ts
- src/pages/journal/__tests__/journal.spec.ts
- src/pages/test-report/__tests__/test-report.spec.ts
- src/pages/waiting-room/__tests__/waiting-room.spec.ts
- Disable Single App Mode when in Practice Mode
- Removed the use of Single App Mode in Health Declaration - It's turned on in the Communication page and turned off in the Back to Office Page
- Tidied up unnecessary imports of ScreenOrientation, DeviceProvider and Insomnia in Unit Tests
> MES-1977- Disable Single App Mode in Practice Tests

- src/pages/journal/journal.html
Change following on from https://github.com/dvsa/mes-mobile-app/pull/455. Added version number when logout button is feature toggled off.
Issue with button text in screenshot is a known issue.
> MES-1640: Display version number when logout button hidden

- src/modules/tests/test-slot-attributes/__tests__/test-slot-attributes.reducer.spec.ts
- src/modules/tests/test-slot-attributes/test-slot-attributes.actions.ts
- src/modules/tests/test-slot-attributes/test-slot-attributes.reducer.ts
- src/pages/office/__tests__/office.spec.ts
- src/pages/office/components/language-preference/__tests__/language-preferences.spec.ts
- src/pages/office/components/language-preference/language-preferences.html
- src/pages/office/components/language-preference/language-preferences.ts
- src/pages/office/office.html
- src/pages/office/office.module.ts
- src/pages/office/office.ts
Adding the welsh and english radio buttons to the office page. They are pre-populated from the welshTest boolean and allow you to change it during the write up.
https://jira.i-env.net/browse/MES-2343
> MES-2343 - Added welsh test toggle to office page

- src/modules/tests/category/__tests__/category.reducer.spec.ts
- src/modules/tests/category/category.actions.ts
- src/modules/tests/category/category.reducer.ts
- src/modules/tests/tests.reducer.ts
- src/pages/journal/journal.effects.ts
- Reducer and action created to store `category` in the state.
Pre-change cloudwatch log
Post change cloudwatch log
> Introducing category to the state

- src/pages/communication-page/components/postal-address/__tests__/postal-address.spec.ts
- src/pages/communication-page/components/postal-address/postal-address.ts
~Fixed a bug where the postal address was being formatted in by referencing the state rather than a separate object.
https://jira.i-env.net/browse/MES-2571
> Mes 2571 format address bug

- src/theme/sass-partials/_row.scss
Add padding to labels on debrief page. See screenshots.
> Add right padding to labels

- package.json
- src/pages/office/office.html
- test/e2e/extended/cat-b-scenarios.feature
- test/e2e/features/99-fulljourney.feature
- test/e2e/step-definitions/debrief-steps.ts
- test/e2e/step-definitions/generic-steps.ts
- test/e2e/step-definitions/office-steps.ts
- test/e2e/step-definitions/testreport-steps.ts
Addition of extra full journey UI tests. 
Also adds in extended regression tests which are to be executed against the release candidate but does not form part of the standard build pipeline. This is the ensure that the pipeline UI test do not exceed 30 minutes but offer a good spread of test coverage offering a high level of confidence in the build.
> Mes 2179 addition of full journey ui tests

- src/pages/journal/components/test-slot/test-slot.ts
- src/pages/journal/journal.selector.ts
- src/pages/journal/journal.ts
- src/providers/slot/slot.ts
- Journal data was previously populating slots in the past fortnight with ```slotData``` from the current day.
- `this.slotContainer.clear()` is now called before a check on `emission` in `createSlots()` to ensure the container does not hold onto irrelevant slots.
- `getRelevantSlots` no longer slices the slots, nor does it handle logic to navigate weekends. This has been added to `canNavigateToNextDay` in `journal.selector.ts`
> Allowing DEs to view previous day

- src/pages/journal/journal.effects.ts
- Removing `loadJournalSuccessEffect` to prevent automatic journal refreshes redirecting DEs to the current date.
- A ticket is being raised to enable manual refreshes to redirect to the current date.
> Feature DES 2546: Fix journal refresh

- mock/local-journal-non-test-activities.json
- mock/local-journal.json
- src/pages/office/components/fault-comment-card/fault-comment-card.html
- src/pages/office/components/fault-comment/__tests__/fault-comment.spec.ts
- src/pages/office/components/fault-comment/fault-comment.ts
Fix the issue where the user can not upload a journal due to validation errors on fields that aren't displayed. This occurs when there are 16 or more driving faults, and a serious or dangerous.
In this case the validator should be removed from the driving faults but this wasn't happening.
> fix issue with validation when 16 driving faults and a serious or dangerous

- src/pages/communication-page/communication.ts
- `conductedLanguage` was not initialised to `English` for English booked tests. This presented issues downstream. 
- `conductedLanguage` is now initialised to `English`.
> Fix initialise conducted language

- src/pages/office/components/activity-code/activity-code.html
- src/pages/office/components/activity-code/activity-code.scss
Set a max height for the termination code select in landscape.
> MES-2504: Correctly size termination code select in landscape

- src/pages/waiting-room-to-car/components/eyesight-failure-confirmation/eyesight-failure-confirmation.html
Jira: https://jira.i-env.net/browse/MES-2511
Continue to debrief/Cancel buttons called the OnSubmit method of WaitingRoomToCarPage, added type="button" to buttons in the eyetestFailureConfirmation component, now it doesn't trigger the parent onSubmit method so it doesn't move to the TestReportPage.
> User now taken to debrief page when failing eye test

- src/pages/debrief/debrief.ts
- src/pages/health-declaration/health-declaration.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.ts
- src/pages/waiting-room/waiting-room.ts
- src/shared/classes/practiceable-base-page.ts
The minification during the build process meant that the method used to find views and remove them from the nav stack failed :(
This PR switches the method of finding the view to use the `id` property of the view instead of the `name`.
In addition, there are extra checks before removing the view to ensure that if the view isn't found, it doesn't call `removeView` with a null value (doing this will remove the first page from the nav stack - which is not good).
> MES-2864 Fix navigation issue on prod builds

- src/pages/test-results-search/components/advanced-search/advanced-search.html
- src/pages/test-results-search/components/advanced-search/advanced-search.ts
Add a clear icon to the date pickers. 
Use `ngModel` binding to simplify how the date is set as it already returns a date string formatted as `YYYY-MM-DD` 👍
> Mes 2900 clear date filters on LDTM search

- package-lock.json
- package.json
- test-config/karma.conf.js
Speed up unit tests by switching to [Karma Parallel](https://www.npmjs.com/package/karma-parallel)
Total time taken to run tests on my machine went from 3 mins 30 secs to 2 mins 2 secs.
> Use karma parallel for running tests

- src/pages/journal/__tests__/journal.effects.spec.ts
- src/pages/journal/journal.effects.ts
Fixed small issue where effect was returning observable of action instead of action causing rekey button not to work and bug out the app.
> Rekey Bug fix

- src/pages/journal/journal-rekey-modal/journal-rekey-modal.html
- test/e2e/step-definitions/journal-steps.ts
With the latest rekey changes, any tests started before the current time (plus test duration) are presented a rekey dialog.
UI will simply start the test as if it was a normal test. Rekey scenarios to follow soon.
> Fix for UI tests following rekey changes as tests in the past show dialog

- test-config/karma.conf.js
Tweaking setting for karma parallel for build pipeline.
Set to 4 executors and increased timeout to 60 seconds.
> Updating test parallel executors

- src/modules/tests/candidate/__tests__/candidate-selector.spec.ts
- src/modules/tests/candidate/candidate.selector.ts
- src/pages/journal/journal.analytics.effects.ts
- src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.analytics.effects.spec.ts
- src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.spec.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.actions.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.analytics.effects.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.ts
- src/pages/waiting-room/__tests__/waiting-room.analytics.effects.spec.ts
- src/pages/waiting-room/__tests__/waiting-room.spec.ts
- src/pages/waiting-room/waiting-room.actions.ts
- src/pages/waiting-room/waiting-room.analytics.effects.ts
- src/pages/waiting-room/waiting-room.ts
- src/providers/analytics/analytics.model.ts
Created analytics effects for the Waiting Room and Waiting Room To Car pages.
For logging screen views and custom dimensions, data is returned from the store.
For logging errors, the error is passed to the action as a payload.
When a form is invalid, the controls are iterated over and a new validation error `xxxx control is invalid` is raised for each control.
> MES-1969 Add analytics to WR and WRTC screens

- src/pages/communication-page/components/postal-address/postal-address.html
- src/providers/test-submission/test-submission.ts
- Fixed issue with comms page not preselecting `By Post` on resume by binding to the `[checked]` attribute
- Fixed issue with text areas being displayed with `undefined` on office page. We were changing the initial state of the reducer with `removeNullFields()` if no other reducer was running on the test. Have used cloneDeep() to create a new object that is used to remove nulls instead of modifying the original.
https://jira.i-env.net/browse/MES-2838
> MES-2838 - Test Journey Bug Fixes

- src/pages/journal/journal.analytics.effects.ts
- src/pages/test-report/__tests__/test-report.analytics.effects.spec.ts
- src/pages/test-report/test-report.analytics.effects.ts
- src/providers/analytics/__mocks__/analytics.mock.ts
- src/providers/analytics/__tests__/analytics.spec.ts
- src/providers/analytics/analytics.model.ts
- src/providers/analytics/analytics.ts
- src/shared/constants/competencies/catb-competencies.ts
- Added effects to log analytics during the test report. 
- Don't log analytics during practice tests.
I return `of({})` rather than `of()` in the effects so that an observable is created and next is emitted.
I haven't used `filter` so that I can always return an observable, allowing me to test that the analytics mock is not called after starting a practice test. Instead I just test for practice mode in the body of the `concatMap` function.
One drawback I see from my tests is that even though I subscribe to the observable, if it's never created, the expect statements won't execute. e.g.
```
// ARRANGE
spyOn(analyticsProviderMock, 'logEvent').and.callThrough();
store$.dispatch(new journalActions.StartTest(123456));
// ACT
actions.next(new testDataActions.AddDrivingFault({
competency: …
```
> MES-2930 add test report analytics

- src/pages/test-report/__tests__/test-report.analytics.effects.spec.ts
- src/pages/test-report/test-report.analytics.effects.ts
- src/providers/analytics/analytics.actions.ts
- Add effects for serious and dangerous faults
- Ensure the analytics effects return a type because as I now understand, returning `of({})` will produce an error `actions must have a type property`... and this breaks the test report 😞  So they now return an action of `AnalyticRecorded or `AnalyticNotRecorded` instead - which is effectively a dummy / void action. But this does mean that tests can now check to see the correct action was returned.
A future PR will need to look at Logs and other Analytics to fix similar issues.
> Mes 2931 serious dangerous faults analytics

- README.md
- e2e-simulator-bdd.conf.js
- test/e2e/step-definitions/generic-steps.ts
- test/e2e/step-definitions/testreport-steps.ts
- test/e2e/step-definitions/waitingroomtocar-steps.ts
Updates to support iOS 12.2. These changes have been made to handle differences in Appium on different iOS 12.2 compared to 12.1.
A bug has been raised with Appium - https://github.com/appium/appium/issues/12682 to get this issue fixed however in the mean time the framework has been updated to handle both versions.
This work around can be removed if the bug fix is implemented by Appium
Note the default iOS version that the automation is run against is still 12.1
> Update ui test support ios12 2

- src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
- src/pages/journal/components/test-slot/test-slot.ts
* Fixing regression from #566 which allowed tests on future days to be started
* Migrate `canStartTest` method to use `DateTime` helper
* Preflight tests https://jenkins.mgmt.mes.dvsacloud.uk/job/mobile-app_build/642/console
> MES-2269 bugfix: Prevent future tests from being started

- src/pages/test-results-search/__tests__/test-results-search.spec.ts
- src/pages/test-results-search/components/advanced-search/advanced-search.ts
- src/pages/test-results-search/test-results-search.html
- src/pages/test-results-search/test-results-search.ts
- src/providers/authentication/user-role.ts
- src/providers/search/__tests__/search.spec.ts
- src/providers/search/search.models.ts
- src/providers/search/search.ts
Hide advanced search when `role` is `'LDTM'`. Kept tab layout as per the design on Abstract.
> MES-2860: Hide advanced search for non-LDTMs (DEs)

- src/pages/test-report/__tests__/test-report.analytics.effects.spec.ts
- src/pages/test-report/test-report.analytics.effects.ts
- src/providers/analytics/analytics.model.ts
- src/providers/analytics/analytics.ts
- src/shared/helpers/format-analytics-text.ts
This is the first of many PRs for changes to analytics, all necessary to split out practice analytics from regular analytics during practice tests and end to end practice.
- Created a helper function to prefix analytics events with "practice mode", "practice test" or nothing depending on the test state.
- Changed the analytics effects so that practice events are logged, but now prefixed e.g. `category: "practice test - test report"` `event: "practice test - add driving fault"` `label: "Junctions - Approach speed"`.
- Updated the tests so that they are much better. Done is passed into the test and they now also fail if the effect does not emit a result.
> Update test report analytics effects and tests to cater for practice mode

- src/pages/waiting-room/__tests__/waiting-room.analytics.effects.spec.ts
- src/pages/waiting-room/waiting-room.analytics.effects.ts
- src/pages/waiting-room/waiting-room.effects.ts
- src/shared/helpers/__tests__/format-analytics-text.spec.ts
Another PR for changes to analytics. This allows practice mode analytics to be identified.
- A helper function to prefix analytics events with "practice mode", "practice test" or nothing depending on the test state.
- Changed the analytics effects so that practice events are logged and prefixed e.g. `category: "practice test - test report"` `event: "practice test - add driving fault"` `label: "Junctions - Approach speed"`.
- Updated the tests so that they are much better. Done is passed into the tests and they now also fail if the effect does not emit a result.
> Analytics for waiting room

- src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.analytics.effects.spec.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.analytics.effects.ts
Another PR to record analytics during practice mode.
Changed the analytics effects so that practice events are logged and prefixed with `"practice mode"`
Updated the tests so that they also fail if the effect does not emit a result.
> Analytics for WRTC screen

- src/modules/tests/candidate/candidate.reducer.ts
- src/pages/communication-page/__tests__/communication.analytics.effects.spec.ts
- src/pages/communication-page/communication.actions.ts
- src/pages/communication-page/communication.analytics.effects.ts
- src/pages/communication-page/communication.module.ts
- src/pages/communication-page/communication.ts
- src/pages/journal/journal.analytics.effects.ts
- src/pages/pass-finalisation/__tests__/pass-finalisation.analytics.effects.spec.ts
- src/pages/pass-finalisation/pass-finalisation.analytics.effects.ts
- src/providers/analytics/analytics.ts
- Update the analytics on the communication and pass finalisation page to record if this is practice mode
- Ensure the Candidate initial state is always set
- Remove unnecessary call to set device ID when setting the current page
> MES-2966 record if in practice mode during analytics on comms and pass page

- src/pages/back-to-office/__tests__/back-to-office.analytics.effects.spec.ts
- src/pages/back-to-office/back-to-office.analytics.effects.ts
- src/pages/debrief/__tests__/debrief.analytics.effects.spec.ts
- src/pages/debrief/__tests__/debrief.effects.spec.ts
- src/pages/debrief/debrief.analytics.effects.ts
- src/pages/health-declaration/__tests__/health-declaration.analytics.effects.spec.ts
- src/pages/health-declaration/health-declaration.analytics.effects.ts
- src/pages/office/__tests__/office.analytics.effects.spec.ts
- src/pages/office/office.analytics.effects.ts
- src/pages/pass-finalisation/__tests__/pass-finalisation.analytics.effects.spec.ts
Update the analytics on the following pages so that practice mode can be distinguished
- debrief
- pass finalisation
- health declaration
- back to office
Added tests for all analytics effects
> MES-2995 update analytics to show practice mode on post test screens

- src/pages/pass-finalisation/__tests__/pass-finalisation.spec.ts
- src/pages/pass-finalisation/pass-finalisation.html
- src/pages/pass-finalisation/pass-finalisation.ts
- test/e2e/features/06-debrief.feature
- test/e2e/step-definitions/debrief-steps.ts
- update `pass-finalisation` validation to enforce a max length of 8 chars for `pass-certificate-numbers`
> MES-2948: fix pass cert length

- test/e2e/extended/cat-b-scenarios.feature
- test/e2e/features/03-waitingroom.feature
- test/e2e/features/04-waitingroomtocar.feature
- test/e2e/features/06-debrief.feature
- test/e2e/features/07-office.feature
- test/e2e/features/99-fulljourney.feature
- test/e2e/step-definitions/journal-steps.ts
Since the introduction of MES-1397 the user is forced to view the candidate details before starting a test where there are checks against the slot.
This update performs the checks before starting test where relevant.
> Updating UI test to complete journal checks before starting tests

- src/pages/candidate-details/candidate-details.ts
- src/pages/communication-page/communication.ts
- src/pages/debrief/components/vehicle-checks-card/vehicle-checks-card.ts
- src/pages/debrief/debrief.ts
- src/pages/health-declaration/health-declaration.ts
- src/pages/journal/components/test-outcome/test-outcome.ts
- src/pages/journal/journal.ts
- src/pages/pass-finalisation/pass-finalisation.ts
- src/pages/test-report/components/competency/competency.ts
- src/pages/test-report/components/controlled-stop/__tests__/controlled-stop.spec.ts
- src/pages/test-report/components/controlled-stop/controlled-stop.ts
- src/pages/test-report/components/driving-fault-summary/driving-fault-summary.ts
- src/pages/test-report/components/eco/eco.ts
- src/pages/test-report/components/manoeuvre-competency/manoeuvre-competency.ts
- src/pages/test-report/components/manoeuvres/manoeuvres.ts
- src/pages/test-report/components/toolbar/toolbar.ts
- src/pages/test-report/components/vehicle-check/vehicle-check.ts
- src/pages/test-report/test-report.ts
- src/pages/test-results-search/test-results-search.ts
- src/pages/view-test-result/__tests__/view-test-result.spec.ts
- src/pages/view-test-result/view-test-result.ts
- src/pages/waiting-room/waiting-room.ts
- src/shared/classes/practiceable-base-page.ts
Refactor subscribe and unsubscribe on observables to clean up on ionViewDidLeave and to subscribe on ionViewWillEnter. If ngOnInit is fired on each page request, the subscribe has been left as is.
[https://jira.i-env.net/browse/MES-2989](https://jira.i-env.net/browse/MES-2989)
> mes-2989 Clean up calls to .unsubscribe from observable subscriptions

- src/pages/communication-page/communication.ts
subscribe was not triggered soon enough on the communications page. It is required for ngOnInit and also ionViewWillEnter as ngOnInit is not called again after it's initial load. Hence the check in ionViewWillEnter to ensure the subscription has not already been set.
> fix for preselecting email radio btn

- src/providers/authentication/__tests__/authentication.spec.ts
- src/providers/authentication/authentication.ts
* Ensure that any callers to `getEmployeeId` in the `AuthenticationProvider` receive the staff number with leading zeroes stripped.
> MES-3063: Strip leading zeroes from staff number once JWT is obtained

- src/pages/office/components/route-number/__tests__/route-number.spec.ts
- src/pages/office/components/route-number/route-number.html
- src/pages/office/components/route-number/route-number.ts
- src/pages/office/office.module.ts
- src/pages/office/office.scss
- Shortened the route number field to match the maximum length of 2 digits
- Restricted the input to only allow numbers
- Added validation to ensure field is a number between 1 and 99, but whilst also allowing a blank value to be saved when pressing "Save and continue later"
> MES-2388 make route number field two digits

- src/components/error-message/error-message.scss
Fix a bug introduced in [PR 613](https://github.com/dvsa/mes-mobile-app/pull/613) that caused various UI problems because the styling for error message `.container` was not nested underneath the error message component.
> BUGFIX - Nest error message container styling

- src/directives/directives.module.ts
- src/pages/office/office.module.ts
- src/pages/waiting-room-to-car/waiting-room-to-car.module.ts
Moved Input Restriction directives to a common module to prevent them being imported twice
> Create directives module

- src/app/app.module.ts
In prod, environment will be undefined. Default `enableDevTools` to `false` in this case.
> Devtools disable in prod fix
