src/components/page-header/page-header.html
src/components/page-header/page-header.scss
src/components/page-header/page-header.ts

+ MES-930 changes to config.xml / ionic.config.json / package.json to fix faling cordova plugin versions dependencies

MES-930 removed username section from page-header component

---

src/pages/pass-data-collection/pass-data-collection.html
src/pages/pass-data-collection/pass-data-collection.ts

* Only allow submission of pass finalisation form once a choice for
provisional provided and certificate number have been input

MES-939: Add validation to pass finalisation submission screen

---

src/components/post-test-summary-section/post-test-summary-section.ts
src/pages/post-test-summary/post-test-summary.html
src/pages/post-test-summary/post-test-summary.ts
src/shared/utils/__tests__/string-utils.spec.ts
src/shared/utils/string-utils.ts
tsconfig.json

* Ensure that route number, weather, show me question, independent driving and physical description are all completed.
* In the event of a fail due to dangerous/serious, ensure that each of those faults has an associated note.
* ~~Disable the submit button unless the above criteria are met.~~
* Give an alert when submit is pressed without the form being complete. Ensure the examiner _can_ defer completing the form if they have another imminent test.

MES-941: Prevent proceed beyond office screen before mandatory fields populated

---

src/components/report-header-v2/report-header-v2.html
src/components/report-header-v2/report-header-v2.scss
src/components/report-header-v2/report-header-v2.ts
src/components/timer/timer.scss
src/pages/all-on-one-v2/all-on-one-v2.html
src/pages/all-on-one-v2/all-on-one-v2.scss
src/pages/all-on-one-v2/all-on-one-v2.ts

Moves S&D buttons and associated functionality into report header component

---

src/pages/all-on-one-v2/all-on-one-v2.html
src/pages/all-on-one-v2/all-on-one-v2.scss

Fixed alignment issues on the row below Manoeuvres on Test Report Screen

MES-913 - Fixed Alignment Issues

---

src/components/report-header-v2/report-header-v2.scss
src/providers/fault-store/fault.reducer.ts

- Ensures that all state is persisted when removing/deleting faults.
- Some styling tweaks to clean up the active state of the S&D buttons.

Defect 1059 remove faults fix

---

src/components/post-test-summary-section/post-test-summary-section.html
src/components/post-test-summary-section/post-test-summary-section.scss
src/components/post-test-summary-section/post-test-summary-section.ts
src/components/textbox-modal/textbox-modal.html
src/pages/post-test-summary/post-test-summary.html
src/pages/post-test-summary/post-test-summary.scss
src/pages/post-test-summary/post-test-summary.ts
src/theme/sass-partials/_buttons.scss
src/theme/sass-partials/_typography.scss
src/theme/variables.scss

This ticket was to apply the new design to the office page (in both portrait and landscape).
- Approved by UX (Oli)
- Approved by PO's (Steve & Gordon)
**Portrait Mode**
**Landscape Mode**

MES-1046 - Office Page Updates

---

src/pages/pass-data-collection/pass-data-collection.html
src/pages/pass-data-collection/pass-data-collection.scss
src/pages/pass-data-collection/pass-data-collection.ts
src/pages/test-result/test-result.html
src/pages/test-result/test-result.ts

Updates to the Pass Finalisation Screen.
PO Sign Off - Complete (Steve and Graham)
QA - ?

MES-1044 - Pass Finalisation Rework

---

.github/PULL_REQUEST_TEMPLATE.md

A proposal of Github pull request template

github pull request template

---

src/pages/health-declaration/health-declaration.html
src/pages/health-declaration/health-declaration.scss
src/pages/health-declaration/health-declaration.ts

UI Rework for the Health Declaration Page
PO sign off given by Steve

MES-1045 - Health Declaration Rework

---

config.xml
src/app/app.module.ts
src/pages/welcome-page/welcome-page.html
src/pages/welcome-page/welcome-page.ts
src/pages/youtube-demo-modal/youtube-demo-modal.html
src/pages/youtube-demo-modal/youtube-demo-modal.scss
src/pages/youtube-demo-modal/youtube-demo-modal.ts

MES-1115
Adds a test popup to the welcome page with a YouTube Video embedded so we can test it on a locked down device.

MES-1115 - Added Embedded YouTube Video

---

src/components/all-on-one-form-sub-element-hold-no-modal/all-on-one-form-sub-element-hold-no-modal.html
src/components/all-on-one-form-sub-element-hold-no-modal/all-on-one-form-sub-element-hold-no-modal.scss
src/components/all-on-one-form-sub-element-hold-no-modal/all-on-one-form-sub-element-hold-no-modal.ts
src/pages/all-on-one-v2/all-on-one-v2.html
src/pages/all-on-one-v2/all-on-one-v2.ts
src/pages/end-test-reason/end-test-reason.html
src/pages/initiate-swap/initiate-swap.html
src/pages/ldtm-mode/ldtm-mode.html
src/pages/pretest-checks/pretest-checks.ts
src/providers/test-summary-metadata/test-summary-metadata.ts

Ticket in jira: **MES-958**
Show me button is visible on the Test Report page. It can be completed and faults can be recorded against it.
It will also contain the fault recorded next to the Tell me question on the Pretest Checks screen.

Mes 958 faults on show me tell me question

---

src/pages/all-on-one-v2/all-on-one-v2.ts

This is an extension of PR #40 (MES-958 Jira ticket number).
There was a bug introduced when DE doesn't select any fault for the **Tell me** question and proceeds to the Test Report. So this PR contains the fix for that.

Fixing a bug around tell me and show me question

---

src/components/components.module.ts
src/components/help-button/help-button.html
src/components/help-button/help-button.scss
src/components/help-button/help-button.ts
src/components/mes-header/mes-header.html
src/components/mes-header/mes-header.ts
src/pages/all-on-one-v2/all-on-one-v2.html
src/pages/all-on-one-v2/all-on-one-v2.ts
src/pages/candidate-info/candidate-info.html
src/pages/candidate-info/candidate-info.ts
src/pages/declaration-consent/declaration-consent.html
src/pages/declaration-consent/declaration-consent.ts
src/pages/health-declaration/health-declaration.html
src/pages/health-declaration/health-declaration.ts
src/pages/journal/journal.html
src/pages/journal/journal.ts
src/pages/pass-data-collection/pass-data-collection.html
src/pages/pass-data-collection/pass-data-collection.ts
src/pages/post-test-summary/post-test-summary.html
src/pages/post-test-summary/post-test-summary.ts
src/pages/test-result/test-result.html
src/pages/test-result/test-result.ts

Adds a help button in the header which opens a popup for that pages relevant help page.

MES-1055- Added Context Sensitive Help

---

src/components/all-on-one-form-sub-element-hold-no-modal/all-on-one-form-sub-element-hold-no-modal.ts
src/pages/declaration-consent/declaration-consent.html

Fixes a lint issue introduced in a previous ticket and removes the bounce on the declaration page

Fixed a Lint Issue and Removed Bounce on Declaration Page

---

config.xml
package-lock.json
package.json

Removing all references to cordova-plugin-ionic

---

src/help/pages/help-debrief/help-debrief.html
src/help/pages/help-finalisation-submission/help-finalisation-submission.html
src/help/pages/help-journal/help-journal.html
src/help/pages/help-test-report/help-test-report.html
src/help/pages/help-waiting-room-to-car/help-waiting-room-to-car.html

* MES-1063 initial waiting room to car page help content
* MES-1063 test report page help content
* MES-1036 debrief page help content
* MES-1063 finalisation and submission help page contents
only journal pages (in normal view and in page context view) but content added for all the apges

MES-1063 initial journal help content

---

src/pages/pretest-checks/pretest-checks.html
src/pages/pretest-checks/pretest-checks.scss

Added validation changes back in

---

src/help/pages/help-section/help-section.html
src/help/pages/help-section/help-section.scss
src/help/pages/help-section/help-section.ts
src/pages/candidate-info/candidate-info.html
src/theme/sass-partials/_typography.scss

Implementing the Help Guide list. Which hast 5 sections and all of them are expandable and they contain additional information which is a generic youtube video at the moment. Because the content is not ready yet.

MES-1052 - Help Guide List

---

src/app/app.scss

Prevent dragging of images throughout the app

---

src/pages/declaration-consent/declaration-consent.html

MES-1189 - Remove taxi and private hire qualification from residency declaration

MES-1189: Remove taxi and private hire qualification from residency declaration

---

src/components/all-on-one-form-sub-element-hold-no-modal/all-on-one-form-sub-element-hold-no-modal.html

MES-1188 - Remove ability to configure button press duration

---

src/components/all-on-one-form-sub-element-hold-no-modal/all-on-one-form-sub-element-hold-no-modal.ts

MES-1190 Manoeuvre fault marking to be limited to a single type of fault

---

package-lock.json
package.json

Fixing build by changing event-stream version

---

src/help/pages/help-debrief/help-debrief.html
src/help/pages/help-finalisation-submission/help-finalisation-submission.html
src/help/pages/help-journal/help-journal.html
src/help/pages/help-test-report/help-test-report.html
src/help/pages/help-waiting-room-to-car/help-waiting-room-to-car.html

MES-1193: Update all the text in the content sensitive help with the latest iteration.
Also considered bringing in stories from sprint 4 upon PO request. These were to ensure we have a context-sensitive help per page, but this needs more content work as a pre-requisite. See comments on https://jira.i-env.net/browse/MES-1231 for more details.

MES-1193: Update help content

---

src/help/pages/help-section/help-section.html

mes-1146: Adding help videos for journal and wrtc

---

src/providers/app-config/app-config.ts

Updating the google analytics id ready for familiarisation build.

---

src/providers/app-config/app-config.ts

Changing google analytics id back to test id.

---

src/help/pages/help-section/help-section.html
src/help/pages/help-section/help-section.scss

MES 1146 - Fixes the blurry youtube videos

---

src/help/pages/help-section/help-section.html

MES-1052 Is a story about adding youtube videos to Help Guide page.
As part of this PR I updated three youtube links, with the relevant videos.
Screenshots

Adding youtube video links

---

src/pages/welcome-page/welcome-page.html
src/providers/app-config/app-config.ts

MES-1284 FINAL FAM DAY DEPLOYMENT - updates showcase video and analytics id

---

src/pages/welcome-page/welcome-page.html

MES-1284 - updates small link at the bottom of the welcome page

---

src/providers/app-config/app-config.ts

MES-1284 - resets analytics id to test

---

package-lock.json

Update to package-lock to resolve package issues

---

README.md

- Add command to load dev config

MES-753 Update Readme

---

src/providers/app-config/app-config.ts

Updated the Config Provider so we only map the data in 1 one 2 places

Small Config Provider Refactor

---

src/providers/app-config/app-config.ts

Fixed issue with always using dev config

---

package-lock.json
package.json
src/app/app.module.ts
src/environment/environment.dev.ts
src/environment/models/environment.model.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment-response.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts
src/providers/authentication/__mocks__/aws4-sign.mock.ts
src/providers/authentication/__mocks__/cognito-identity-wrapper.mock.ts
src/providers/authentication/__tests__/authentication.spec.ts
src/providers/authentication/__tests__/interceptor.spec.ts
src/providers/authentication/authentication.ts
src/providers/authentication/cognitoIdentityWrapper.ts
src/providers/authentication/interceptor.ts
tsconfig.json

Implements token verification into the MES mobile app: In a nutshell we are using the token provided by Authenticator from login to generate temporary credentials that can be used to access our microservices in AWS. This is only implemented when running on iOS.
- Fixes the `resourceUrl` param in authentication settings to be the application ID.
- Adds the `aws-sdk` for obtaining IAM credentials from Cognito and `aws4` for signing http requests using [AWS Signature 4 Signing Process ](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)
- Adds an app-wide [HTTP Interceptor](https://angular.io/guide/http#intercepting-requests-and-responses), this will act as middleware for all http requests adding the required authentication headers.

Feature mes 1357 token verification

---

config.xml
package-lock.json
package.json

[Post from Ionic](https://ionic.zendesk.com/hc/en-us/articles/360015176994-2019-01-03-Security-Alert-for-cordova-plugin-ionic-webview) about the vulnerability.
Once merged, developers will need to re-install this plugin manually on their machines.

MES-1420 - Address security vulnerability with cordova-plugin-ionic-webview

---

src/pages/candidate-details/__tests__/candidate-details.selector.spec.ts
src/pages/candidate-details/candidate-details.selector.ts
src/pages/candidate-details/candidate-details.ts
src/pages/journal/__tests__/journal.reducer.spec.ts
src/pages/journal/__tests__/journal.selector.spec.ts
src/pages/journal/__tests__/journal.spec.ts
src/pages/journal/journal.actions.ts
src/pages/journal/journal.effects.ts
src/pages/journal/journal.model.ts
src/pages/journal/journal.reducer.ts
src/pages/journal/journal.selector.ts
src/pages/journal/journal.ts
src/providers/slot-selector/__tests__/slot-selector.spec.ts
src/providers/slot-selector/slot-selector.ts

Cleaning up the Store. We used to have `data` field on the journal which held the `testSlots`. But `slots` was introduced which will be the place where we keep the activity slots for the journal.

Store clean up

---

src/common/test-category.ts

Adding additional test categories to the test category enum

MES-1466 - Added Additional Test Categories to Enum

---

src/providers/journal/__mocks__/journal.mock.ts

One test was failing because of the current date. Adding moment to the mock data fixes that.

Adding current date to mock journal data

---

mock/local-journal.json
package.json
src/pages/journal/__mocks__/journal-slots-data.mock.ts

Fixes json import and referencing of local json

---

bin/update-mock-data.ts
mock/local-journal.json

- Updates to the code so that both the journal service version and this version are the same
- Fixes to the mock object so it matches what we expect from the ExaminerWorkSchedule.

MES-1452 - Updated script to use the same code as the journal service

---

mock/local-journal.json
src/pages/journal/components/journal-navigation/__tests__/journal-navigation.spec.ts
src/pages/journal/components/journal-navigation/journal-navigation.html

Unit tests for the journal navigation DOM.

Implementing unit tests for journal navigation

---

bin/update-mock-data.ts
src/environment/environment.dev.ts
src/environment/environment.local.ts
src/environment/environment.staging.ts
src/environment/models/environment.model.ts
src/pages/journal/__mocks__/journal-slots-data.mock.ts
src/pages/journal/__tests__/journal.effects.spec.ts
src/pages/journal/__tests__/journal.selector.spec.ts
src/pages/journal/components/journal-navigation/__mocks__/journal-slots-data.mock.ts
src/pages/journal/components/journal-navigation/__tests__/journal-navigation.spec.ts
src/pages/journal/journal.effects.ts
src/pages/journal/journal.reducer.ts
src/pages/journal/journal.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment-response.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts
src/providers/slot/__mocks__/journal-slots-missing-days-mock.json
src/providers/slot/__tests__/slot.spec.ts
src/providers/slot/slot.ts

Implementing the functionality of inserting empty days and also the navigation logic when it's a simple weekday or it's a Friday.

Implementing the navigation through the weekends

---

src/providers/slot/__tests__/slot.spec.ts

skips broken slot provider test

---

src/app/app.module.ts
src/environment/environment.dev.ts
src/environment/environment.local.ts
src/environment/environment.staging.ts
src/environment/models/environment.model.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment-response.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts
src/providers/logging/__mocks__/logging.mock.ts
src/providers/logging/__tests__/logging.spec.ts
src/providers/logging/logging.constants.ts
src/providers/logging/logging.ts
src/providers/url/__mocks__/url.mock.ts
src/providers/url/__tests__/url.spec.ts
src/providers/url/url.ts

Adds the logging service to the mobile application so we are able to send logs to the Logging Microservice

Mes 1527 - Logging Service

---

e2e-simulator-bdd.conf.js
package-lock.json
package.json
test/e2e/features/02-journal.feature
test/e2e/step-definitions/generic-steps.ts
test/e2e/step-definitions/journal-steps.ts
test/e2e/test.config.ts

Adding more journal ui tests

---

src/common/__tests__/date-time.spec.ts
src/common/date-time.ts

Combine dateDiff and daysUntil methods from date-time component

---

src/pages/journal/journal.reducer.ts

Bug fix after date time method was renamed

---

test/e2e/step-definitions/generic-steps.ts
test/e2e/step-definitions/journal-steps.ts
test/e2e/test.config.ts

Updates to UI tests to reflect updates from mes-1566

---

src/pages/journal/journal.html
test/e2e/step-definitions/generic-steps.ts

Update to use new location for employee id

---

src/providers/logging/__tests__/logging.spec.ts
src/providers/logging/logging.constants.ts

Updated the log object so it contains a timestamp and allows us to add any number of other strings to it. (Matches the Microservice Object)

MES-1730 - Updated Log Object

---

mock/local-journal.json
src/pages/candidate-details/__tests__/candidate-details.selector.spec.ts
src/pages/candidate-details/candidate-details.html
src/pages/candidate-details/candidate-details.model.ts
src/pages/candidate-details/candidate-details.selector.ts

Implementing a new row on Candidate Details page which holds information about the entitlement check.

Implementing entitlement check on the candidate details page

---

clean-rebuild.sh
src/environment/environment.dev.ts
src/environment/environment.local.ts
src/environment/environment.production.ts
src/environment/environment.staging.ts
src/environment/environment.uat.ts
src/environment/models/environment.model.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts

Removes old AzureAD config and corrects clean-rebuild.sh commands

---

src/theme/sass-partials/_buttons.scss

Changing the height to min-height so that the 'Start Test' button size increases when the font size increases.

Bug fix on Start Test button resizing

---

mock/local-journal.json

Fixes select next day unit test

---

src/environment/environment.local.ts
src/environment/models/environment.model.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts

Branch passes build on jenkins - https://jenkins.mgmt.mes.dvsacloud.uk/job/mobile-app_build/68/

Fixes TS compiler error: Adds new approvedDeviceIdentifiers key to local models/mocks

---

config.xml
package-lock.json
package.json
src/karmaGlobalMocks.js
src/pages/test-report/test-report.ts
src/providers/device/__tests__/device.spec.ts
src/providers/device/device.ts
test-config/karma.conf.js

- MES-500 Disable notifications on the test report page when the device is Supervised via MDM
- Improve tests for device provider

MES-500 inhibit notifications on supervised devices

---

mock/local-journal.json
test/e2e/features/02-journal.feature
test/e2e/step-definitions/journal-steps.ts
test/e2e/test.config.ts

Fixing existing tests so that it reads the correct data.
Implementing new commits to cover the different slot types.

End to end tests for journal

---

config.xml
package-lock.json
package.json
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/test-report.module.ts
src/pages/test-report/test-report.ts
src/shared/mocks/insomnia.mock.ts

Enable insomnia plugin on test report page

Add insomnia plugin and enable on test report page

---

README.md
config.xml
mock/local-journal.json
package-lock.json
package.json
src/pages/candidate-details/__tests__/candidate-details.selector.spec.ts
src/pages/candidate-details/__tests__/candidate-details.spec.ts
src/pages/candidate-details/candidate-details.html
src/pages/candidate-details/candidate-details.model.ts
src/pages/candidate-details/candidate-details.scss
src/pages/candidate-details/candidate-details.selector.ts
src/pages/candidate-details/candidate-details.ts
src/pages/journal/__tests__/journal.spec.ts
src/pages/journal/components/empty-slot/__tests__/empty-slot.spec.ts
src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/test-report.module.ts
src/pages/test-report/test-report.ts
src/shared/mocks/insomnia.mock.ts
src/shared/mocks/screen-orientation.mock.ts
test/e2e/features/02-journal.feature
test/e2e/step-definitions/journal-steps.ts

mes-1739 special requirements split from comments.

---

package.json
src/environment/environment.perf.ts

Add config for running the app in the perf environment

---

mock/local-journal-non-test-activities.json
mock/local-journal.json
src/pages/candidate-details/__tests__/candidate-details.selector.spec.ts
src/pages/candidate-details/candidate-details.html
src/pages/candidate-details/candidate-details.model.ts
src/pages/journal/components/empty-slot/__tests__/empty-slot.spec.ts
src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
src/providers/slot/__tests__/slot.spec.ts

previousCancellation change to string array from initiator. 

---

test/e2e/step-definitions/generic-steps.ts

Update to normalise space and ignore whitespace in text comparison.

---

src/environment/environment.local.ts
src/environment/models/environment.model.ts
src/pages/journal/components/test-outcome/__tests__/test-outcome.spec.ts
src/pages/journal/components/test-outcome/test-outcome.html
src/pages/journal/components/test-outcome/test-outcome.ts
src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
src/pages/journal/components/test-slot/test-slot.html
src/pages/journal/components/test-slot/test-slot.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment-response.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts

Now have the ability to enable and disable the start test button based on configuration

MES-1756 - Disable Start Button

---

mock/README.md
mock/local-journal.json
test-config/karma.conf.js

Also adds a readme to mock dir to remind people about having a test slot for tomorrow.

Enables chromeheadless for unit tests

---

src/app/app.component.ts

Fixed the bug where the font wasn't updating to the accessibility settings on first launch.
https://jira.i-env.net/browse/MES-1801

MES-1801 Fixed font update bug on app first launch

---

src/pages/waiting-room/waiting-room.html

* Restore navigation beyond Waiting Room page

Restore navigation beyond Waiting Room page

---

src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/competency/__tests__/competency.spec.ts
src/pages/test-report/components/competency/competency.html
src/pages/test-report/components/competency/competency.scss
src/pages/test-report/components/competency/competency.ts
src/pages/test-report/test-report.html
src/pages/test-report/test-report.module.ts
src/pages/test-report/test-report.ts

Pretty button to use for competencies on the test report

MES-1250 - Competency Button

---

src/pages/waiting-room/__tests__/waiting-room.spec.ts

Fix Lint Issues

---

README.md
src/pages/waiting-room/waiting-room.html
test/e2e/features/02-journal.feature
test/e2e/features/03-waitingroom.feature
test/e2e/step-definitions/waitingroom-steps.ts

* Test that a test for tomorrow cannot be started
* Navigate to the Waiting Room page and make sure the candidate is correctly populated

MES-995: Start a test E2E tests (MES-1904)

---

src/app/app.scss
src/pages/test-report/components/competency/competency.scss
src/pages/test-report/test-report.html
src/pages/test-report/test-report.scss
src/pages/test-report/test-report.ts
src/theme/sass-partials/_spacing.scss

Adds the layout and all competencies to the test report page

MES-1813 - View all Competencies

---

mock/local-journal.json
src/app/app.scss
src/components/signature-area/__tests__/signature-area.spec.ts
src/components/signature-area/signature-area.html
src/components/signature-area/signature-area.scss
src/components/signature-area/signature-area.ts
src/pages/component-library/component-library.ts
src/pages/waiting-room/waiting-room.html
src/pages/waiting-room/waiting-room.module.ts
src/pages/waiting-room/waiting-room.scss
src/pages/waiting-room/waiting-room.ts
src/theme/sass-partials/_checkbox.scss
src/theme/sass-partials/_validation.scss

mes-1249 proceed to vehicle check
e2e tests pending
- [] branch rebased against the latest develop
- [] commits are squashed

Mes 1249 Validation of waiting room fields

---

test/e2e/step-definitions/generic-steps.ts

Update to wait events to improve stability of tests

---

src/pages/test-report/components/competency/__tests__/competency.spec.ts
src/pages/test-report/components/competency/competency.html
src/pages/test-report/components/competency/competency.scss
src/pages/test-report/components/competency/competency.ts
src/pages/test-report/components/fault-counter/__tests__/fault-counter.spec.ts
src/pages/test-report/components/fault-counter/fault-counter.html
src/pages/test-report/components/fault-counter/fault-counter.scss
src/pages/test-report/components/fault-counter/fault-counter.ts
src/pages/test-report/test-report.module.ts
src/pages/waiting-room/waiting-room.html
src/providers/hammer/__tests__/hammer.spec.ts

MES-76: Style driving fault counters (MES-1913)

---

src/pages/waiting-room/waiting-room.html
test/e2e/features/03-waitingroom.feature
test/e2e/step-definitions/generic-steps.ts

- [] branch rebased against the latest develop

mes-1249 e2e tests for waiting room validation

---

src/modules/tests/pre-test-declarations/__tests__/pre-test-declarations.reducer.spec.ts
src/modules/tests/pre-test-declarations/pre-test-declarations.actions.ts
src/modules/tests/pre-test-declarations/pre-test-declarations.reducer.ts
src/pages/test-report/components/competency/competency.scss
src/pages/waiting-room/__tests__/waiting-room.spec.ts
src/pages/waiting-room/waiting-room.html
src/pages/waiting-room/waiting-room.scss
src/pages/waiting-room/waiting-room.ts

* Ensure Waiting Room screen is cleared when going back to Journal
* Fix bouncing of Waiting Room page by preventing content overflow

Sprint 11 Waiting Room hotfixes

---

src/pages/login/__tests__/login.spec.ts

Fixes cordova console errors when running tests

Use Network Provider Mock in Login Tests

---

src/pages/waiting-room/__tests__/waiting-room.spec.ts

mes-1249 unit test for waiting room form

---

mock/local-journal.json
src/pages/candidate-details/candidate-details.html

Small bug in the entitlement check where it wasn't using "mes-data" css class so font size was slightly off.
https://jira.i-env.net/browse/MES-1896

MES-1896 - Fixed entitlement check font size problem

---

src/pages/waiting-room-to-car/waiting-room-to-car.html
src/pages/waiting-room-to-car/waiting-room-to-car.scss

Apologies for removing this, forgot that not having this would block testing of test report! Adding a simple `navPush`.

Restore button to proceed from WRTC to test report

---

src/pages/pass-finalisation/pass-finalisation.ts

Ensure the getTests selector is called on the pass finalisation component

Call the get tests selector before getting the current test

---

src/pages/debrief/__tests__/debrief.spec.ts
src/pages/debrief/debrief.html
src/pages/debrief/debrief.scss
src/pages/debrief/debrief.ts

Added 'End Debrief' button to bottom of debrief page

MES-1093 - confirm test outcome

---

src/pages/test-report/test-report.scss

overlay fix

---

src/pages/test-report/components/competency/competency.html
src/pages/test-report/components/competency/competency.scss
src/pages/test-report/components/fault-counter/fault-counter.scss
src/pages/test-report/components/serious-fault-badge/serious-fault-badge.scss
src/pages/test-report/components/serious-tooltip/serious-tooltip.scss
src/pages/test-report/components/toolbar/toolbar.scss
src/pages/test-report/test-report.scss

- Fixed positioning on the serious mode tooltip
- Fixed background color on competencies with a serious fault
- Center Text for Competencies
- Center Labels in Driving Fault and Serious Fault Badges
- Fixed page bounce

Fix Test Report CSS Issues

---

README.md
test/e2e/features/01-login.feature
test/e2e/features/02-journal.feature
test/e2e/features/03-waitingroom.feature

Initial addition of smoke test tags for UI tests

---

mock/local-journal.json
src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
src/modules/tests/test_data/__tests__/test-data.selector.spec.ts
src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/modules/tests/test_data/test-data.selector.ts
src/pages/journal/__tests__/journal.effects.spec.ts
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/competency-with-modal/competency-with-modal.html
src/pages/test-report/components/legal-requirements/__tests__/legal-requirements.spec.ts
src/pages/test-report/components/legal-requirements/legal-requirements.html
src/pages/test-report/components/legal-requirements/legal-requirements.scss
src/pages/test-report/components/legal-requirements/legal-requirements.ts
src/pages/test-report/test-report.html
src/pages/test-report/test-report.module.ts

Placing the Legal Requirements section on the test report page.
These buttons can be toggled whenever the candidate has finished a requirement. After toggling the grey checkbox turns green. And if pressed again it goes back to grey.
Also implementing the logging of these actions.

MES-1016 - Record Legal Requirements

---

src/components/components.module.ts
src/components/screen-lock-indicator/__tests__/screen-lock-indicator.spec.ts
src/components/screen-lock-indicator/lock-screen-indicator.html
src/components/screen-lock-indicator/lock-screen-indicator.scss
src/components/screen-lock-indicator/lock-screen-indicator.ts
src/modules/tests/post-test-declarations/__tests__/post-test-declarations.reducer.spec.ts
src/modules/tests/post-test-declarations/__tests__/post-test-declarations.selector.spec.ts
src/modules/tests/post-test-declarations/post-test-declarations.actions.ts
src/modules/tests/post-test-declarations/post-test-declarations.reducer.ts
src/modules/tests/post-test-declarations/post-test-declarations.selector.ts
src/modules/tests/tests.reducer.ts
src/pages/health-declaration/__tests__/health-declaration.spec.ts
src/pages/health-declaration/health-declaration.html
src/pages/health-declaration/health-declaration.module.ts
src/pages/health-declaration/health-declaration.scss
src/pages/health-declaration/health-declaration.ts
src/pages/waiting-room/__tests__/waiting-room.spec.ts
src/pages/waiting-room/waiting-room.html
src/pages/waiting-room/waiting-room.scss

Create the main form for the health declaration page.
https://jira.i-env.net/browse/MES-93

MES-93 - Health Declaration Form

---

src/pages/pass-finalisation/pass-finalisation.html
src/pages/pass-finalisation/pass-finalisation.scss
src/pages/pass-finalisation/pass-finalisation.ts

Add validation to the pass finalisation page, similar to the the WRTC page.

MES-1922 validate pass completion page

---

src/pages/test-report/components/competency/__tests__/competency.spec.ts
src/pages/test-report/components/competency/competency.scss
src/pages/test-report/components/competency/competency.ts

MES-1012 - Changed Serious Button Styles after PO Review

---

src/modules/tests/tests.reducer.ts
src/modules/tests/vehicle-checks/__tests__/vehicle-checks.reducer.spec.ts
src/modules/tests/vehicle-checks/vehicle-checks.actions.ts
src/modules/tests/vehicle-checks/vehicle-checks.reducer.ts
src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.spec.ts
src/pages/waiting-room-to-car/waiting-room-to-car.html
src/pages/waiting-room-to-car/waiting-room-to-car.ts

* Simple action dispatch + reduce to store the selected tell me question whenever it changes
* New state sample:
```
{
'1005': {
...
vehicleChecks: {
tellMeQuestionCode: 'T3',
tellMeQuestionDescription: 'Tell me how you make sure your head restraint is correctly adjusted so it provides the best protection in the event of a crash.'
}
}
}
```

MES-2019: Store the selected tell me question (MES-1907)

---

mock/local-journal.json
src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
src/modules/tests/test_data/__tests__/test-data.selector.spec.ts
src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/modules/tests/test_data/test-data.selector.ts
src/pages/login/login.module.ts
src/pages/test-report/components/competency/__tests__/competency.spec.ts
src/pages/test-report/components/competency/competency.html
src/pages/test-report/components/competency/competency.ts
src/pages/test-report/components/dangerous-fault-badge/dangerous-fault-badge.html
src/pages/test-report/components/dangerous-fault-badge/dangerous-fault-badge.scss
src/pages/test-report/components/dangerous-fault-badge/dangerous-fault-badge.ts
src/pages/test-report/test-report.module.ts

Recording a dangerous fault against a competency.
Marking the competency button with the Dangerous Fault Badge.

Mes-2011 - Add dangerous fault to competency

---

src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.spec.ts
src/pages/waiting-room-to-car/waiting-room-to-car.html
src/pages/waiting-room-to-car/waiting-room-to-car.module.ts
src/pages/waiting-room-to-car/waiting-room-to-car.scss
src/pages/waiting-room-to-car/waiting-room-to-car.ts

* Prevent proceeding to Test Report when changing Tell Me question after already having marked it
* Ensure the Tell Me question selector is large enough to show all questions without expansion from starting size
* Set Tell Me question row label to always align with question selector, even when marking radios are visible
* Ensure Tell Me question marking radios are aligned with all other radios
* Enable orientation lock, single app mode and sleep prevention

Various Waiting Room To Car bugfixes

---

src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/modules/tests/test_data/test-data.selector.ts
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/examiner-takes-action/__tests__/eta.spec.ts
src/pages/test-report/components/examiner-takes-action/eta.html
src/pages/test-report/components/examiner-takes-action/eta.scss
src/pages/test-report/components/examiner-takes-action/eta.ts
src/pages/test-report/test-report.html
src/pages/test-report/test-report.module.ts

mes-77 Examiner must be able to record if a verbal or physical action is required 
- [] Any new reusable component/widget added to component library on Confluence

examiner takes action

---

config.xml

Stop webview resizing when keyboard visible

Stop webview resizing when keyboard visible

---

mock/local-journal.json
src/components/dangerous-fault-badge/__tests__/dangerous-fault-badge.spec.ts
src/pages/test-report/components/competency/__tests__/competency.spec.ts
src/pages/test-report/components/competency/competency.html
src/pages/test-report/components/competency/competency.scss
src/pages/test-report/components/competency/competency.ts

Implementing the functionality to record serious or driving faults with tap or press or hold.
Also writing unit tests for this feature.

Record serious/dangerous fault on tap & press & hold

---

src/pages/test-report/components/dangerous-tooltip/dangerous-tooltip.html
src/pages/test-report/components/dangerous-tooltip/dangerous-tooltip.scss
src/pages/test-report/components/dangerous-tooltip/dangerous-tooltip.ts
src/pages/test-report/components/driving-fault-summary/driving-fault-summary.html
src/pages/test-report/components/driving-fault-summary/driving-fault-summary.scss
src/pages/test-report/components/serious-tooltip/serious-tooltip.html
src/pages/test-report/components/serious-tooltip/serious-tooltip.scss
src/pages/test-report/components/serious-tooltip/serious-tooltip.ts
src/pages/test-report/components/toolbar/__tests__/toolbar.spec.ts
src/pages/test-report/components/toolbar/toolbar.html
src/pages/test-report/components/toolbar/toolbar.scss
src/pages/test-report/components/toolbar/toolbar.ts
src/pages/test-report/test-report.actions.ts
src/pages/test-report/test-report.html
src/pages/test-report/test-report.reducer.ts
src/pages/test-report/test-report.scss
src/pages/test-report/test-report.selector.ts
src/pages/test-report/test-report.ts

mes-1014 remove fault (fault mode)
**Black border added on Nad's request**

initial commit for remove fault mode

---

src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/pages/test-report/components/competency/__tests__/competency.spec.ts
src/pages/test-report/components/competency/competency.html
src/pages/test-report/components/competency/competency.ts
src/pages/test-report/test-report.html
src/pages/test-report/test-report.scss
src/pages/test-report/test-report.ts

Test report now has the ability to remove and add Driving, Serious and Dangerous faults

mes-1014 remove driving faults and mes-1924 remove serious and dangerous faults

---

src/pages/test-report/components/driving-fault-summary/driving-fault-summary.scss
src/pages/test-report/components/tick-indicator/tick-indicator.scss
src/pages/test-report/components/toolbar/toolbar.scss
src/pages/test-report/test-report.html
src/pages/test-report/test-report.scss

- Removes the typo “Z” in front of the test requirements section title
- Adds a little spacing between the D/F and the circular counter
- Centers the tick icon for manoeuvres and test requirements when running on ios
- Aligns the toolbar elements with the elements on the rest of the page
- Makes the overlay slightly darker and quicker to appear

styling improvement tweaks

---

src/pages/test-report/components/dangerous-tooltip/dangerous-tooltip.scss

Very quick tweak for S&T to fix the font colour of the dangerous fault tool tip

Fixes font colour for dangerous tool tip

---

mock/local-journal.json
src/modules/tests/test-status/__tests__/test-status.reducer.spec.ts
src/modules/tests/test-status/test-status.actions.ts
src/modules/tests/test-status/test-status.reducer.ts
src/pages/back-to-office/__tests__/back-to-office.spec.ts
src/pages/back-to-office/back-to-office.ts

MES-2075: Mark test as decided once we reach the back-to-office page (MES-2028)

---

src/app/app.html

Prevents users from swiping to go back, this was possible even on the declaration page 😱

Disables swipe back globally

---

src/pages/test-report/components/competency/__tests__/competency.spec.ts
src/pages/test-report/components/competency/competency.html
src/pages/test-report/components/competency/competency.ts

- Fixes the ripple effect so that it only gets applied when adding faults via the press and hold gesture.
- Renames the method that does this so its clearer.

Ripple effect fix

---

src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
src/modules/tests/test_data/__tests__/test-data.selector.spec.ts
src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/modules/tests/test_data/test-data.selector.ts
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/controlled-stop/__tests__/controlled-stop.spec.ts
src/pages/test-report/components/controlled-stop/controlled-stop.html
src/pages/test-report/components/controlled-stop/controlled-stop.scss
src/pages/test-report/components/controlled-stop/controlled-stop.ts
src/pages/test-report/components/legal-requirements/legal-requirements.ts
src/pages/test-report/components/test-report-components.module.ts
src/pages/test-report/test-report.html
src/pages/test-report/test-report.ts

This PR adds the ability to mark a controlled stop as completed or not completed on the test report

MES-2046 - Implementing controlled stop selection

---

mock/local-journal.json
src/app/app.module.ts
src/modules/tests/test-status/__tests__/test-status.effects.spec.ts
src/modules/tests/test-status/test-status.effects.ts
src/modules/tests/tests.module.ts
src/providers/test-persistence/__mocks__/test-persistence.mock.ts
src/providers/test-persistence/__tests__/test-persistence.spec.ts
src/providers/test-persistence/test-persistence.ts

* Introduce effect listening to when the a test's status changes to Decided
* Call into a provider which will persist what's currently in the `tests` key in the store

MES-2027: Persist deferred tests

---

package-lock.json
package.json

Move Angular compiler-cli to a depDependency to fix pipeline npm audit failure

---

src/pages/test-report/components/competency/__tests__/competency.spec.ts
src/pages/test-report/components/competency/competency.html
src/pages/test-report/components/competency/competency.scss
src/pages/test-report/components/competency/competency.ts
src/pages/test-report/components/controlled-stop/controlled-stop.html
src/pages/test-report/components/controlled-stop/controlled-stop.scss
src/pages/test-report/components/examiner-takes-action/eta.html
src/pages/test-report/components/examiner-takes-action/eta.scss
src/pages/test-report/components/legal-requirements/legal-requirements.html
src/pages/test-report/components/legal-requirements/legal-requirements.scss
src/theme/sass-partials/_buttons.scss
src/theme/sass-partials/_spacing.scss

Based on feedback from a previous PR
Refactor to create a common style for buttons on the test report and a tidy up of some of the styles

Styling Refactor

---

test/e2e/step-definitions/generic-steps.ts
test/e2e/step-definitions/journal-steps.ts

Updates to improve stability by increased checking

---

config.xml
package-lock.json
package.json
src/karmaGlobalMocks.js
src/providers/app-config/__tests__/app-config.spec.ts
src/providers/app-config/app-config.ts

This PR adds a new way of getting configuration in the app. If the app is running on an ios device it will try and check for configuration from an MDM provider , if non exists it will fall back to the current system

MES-2080 - Get Config from MDM

---

mock/local-journal.json

Updating mock journal data for tests

---

mock/local-journal.json
src/app/app.module.ts
src/modules/tests/test-summary/test-summary.actions.ts
src/modules/tests/test-summary/test-summary.reducer.ts
src/pages/office/__tests__/office.spec.ts
src/pages/office/office.html
src/pages/office/office.scss
src/pages/office/office.ts
src/providers/weather-conditions/weather-condition.ts
src/providers/weather-conditions/weather-conditions.constants.ts
src/providers/weather-conditions/weather-conditions.model.ts
src/theme/sass-partials/_alert.scss

* Add `ion-select` to display potential weather conditions in multi-select mode
* Re-style the multi-select alert/checkboxes to fit designs more closely
* Create provider for weather conditions constants
* Make weather conditions selector participate in Office form validation

MES-1102: Record weather conditions

---

mock/local-journal.json
src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/modules/tests/test_data/test-data.selector.ts
src/pages/test-report/components/manoeuvre-competency/__tests__/manoeuvre-competency.spec.ts
src/pages/test-report/components/manoeuvre-competency/manoeuvre-competency.html
src/pages/test-report/components/manoeuvre-competency/manoeuvre-competency.ts
src/pages/test-report/components/manoeuvres-popover/manoeuvres-popover.html
src/pages/test-report/components/manoeuvres-popover/manoeuvres-popover.ts

- Recording a serious or a dangerous fault on manoeuvres.
- Toggling the mode of the test-report after recording a fault.
- There is possibility to record only one type of fault and if that type is a simple driving fault then it can be only one.

Recording a serious/dangerous fault on manoeuvres

---

test/e2e/features/03-waitingroom.feature

Correction to driving licence format following mes-2144

---

src/modules/tests/post-test-declarations/__tests__/post-test-declarations.reducer.spec.ts
src/modules/tests/pre-test-declarations/__tests__/pre-test-declarations.reducer.spec.ts
src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/pages/test-report/components/controlled-stop/__tests__/controlled-stop.spec.ts
src/pages/test-report/components/controlled-stop/controlled-stop.html
src/pages/test-report/components/controlled-stop/controlled-stop.ts
test-config/karma.conf.js

- Add and remove faults from controlled stop
- Stop state from being mutated in tests

MES-1849 - Controlled stop remove fault

---

src/modules/tests/test-summary/test-summary.selector.ts
src/pages/office/__tests__/office.spec.ts
src/pages/office/components/route-number/route-number.html
src/pages/office/components/weather-conditions/weather-conditions.html
src/pages/office/components/weather-conditions/weather-conditions.ts
src/pages/office/office.html
src/pages/office/office.module.ts
src/pages/office/office.ts

* Extract weather conditions capture into a dedicated presentational component
* Have `WeatherConditionsComponent` handle it's form validation and repopulation of the form value
* Emit an event back to the Office page when weather conditions change to update the store

MES-2159: Extract presentational component for weather conditions which repopulates form (MES-1129)

---

mock/local-journal.json
src/pages/journal/components/test-outcome/test-outcome.ts
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/test-report-components.module.ts
src/pages/test-report/components/vehicle-check/__tests__/vehicle-check.spec.ts
src/pages/test-report/components/vehicle-check/vehicle-check.html
src/pages/test-report/components/vehicle-check/vehicle-check.scss
src/pages/test-report/components/vehicle-check/vehicle-check.ts
src/pages/test-report/test-report.html

Creating Vehicle Check component and displaying it on the Test Report page.

Displaying vehicle check on Test Report

---

src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/eco/eco.html
src/pages/test-report/components/eco/eco.scss
src/pages/test-report/components/eco/eco.ts
src/pages/test-report/components/test-report-components.module.ts
src/pages/test-report/test-report.html
src/theme/sass-partials/_buttons.scss

- Create the buttons for the ECO components

Mes 2190 create eco buttons

---

src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/pages/test-report/components/eco/__tests__/eco.spec.ts
src/pages/test-report/components/eco/eco.html
src/pages/test-report/components/eco/eco.scss
src/pages/test-report/components/eco/eco.ts

- Add functionality to the ECO buttons

Mes 2191 add eco button functionality

---

src/pages/test-report/test-report.html
src/pages/test-report/test-report.ts

- Adds End Test Button
- Removes the Eco Control & Planning Buttons from the top toolbar (buttons now work)
- Moved Pass Test & Fail Test to the left of the toolbar

MES-2170 - Added End Test Button

---

src/pages/test-report/components/vehicle-check/__tests__/vehicle-check.spec.ts
src/pages/test-report/components/vehicle-check/vehicle-check.ts

Selecting tell me question outcome
Displaying badge if there was any driving fault

MES-2188 Display tell me question fault on Vehicle Checks

---

src/pages/test-report/components/competency-button/competency-button.ts
src/pages/test-report/components/test-report-components.module.ts
src/pages/test-report/components/timer/__tests__/timer.spec.ts
src/pages/test-report/components/timer/timer.html
src/pages/test-report/components/timer/timer.scss
src/pages/test-report/components/timer/timer.ts
src/pages/test-report/components/toolbar/__tests__/toolbar.spec.ts
src/pages/test-report/components/toolbar/toolbar.html

Adds a timer to the test report
User can start, pause and restart the timer by tapping on it. Screenshots below.
**Default state**
**Paused state**
**Active state**

MES-88 - Test report timer

---

src/modules/tests/test_data/__tests__/test-data.reducer.spec.ts
src/modules/tests/test_data/__tests__/test-data.selector.spec.ts
src/modules/tests/test_data/test-data.actions.ts
src/modules/tests/test_data/test-data.reducer.ts
src/modules/tests/test_data/test-data.selector.ts
src/pages/test-report/components/eco/eco.ts
src/pages/test-report/components/vehicle-check/__tests__/vehicle-check.spec.ts
src/pages/test-report/components/vehicle-check/vehicle-check.html
src/pages/test-report/components/vehicle-check/vehicle-check.ts
src/pages/waiting-room-to-car/__tests__/waiting-room-to-car.spec.ts
src/shared/models/competency-outcome.ts

- Record serious fault against the show me question.
- Override tell me question driving fault badge with a serious fault badge after recording a serious fault on the show me question

MES-2205 Record serious fault against show me question

---

src/components/end-test-link/__tests__/end-test-link.spec.ts
src/components/end-test-link/end-test-link.ts
src/components/terminate-test-modal/__tests__/terminate-test-modal.spec.ts
src/components/terminate-test-modal/terminate-test-modal.html
src/components/terminate-test-modal/terminate-test-modal.ts
src/pages/debrief/__tests__/debrief.spec.ts
src/pages/debrief/debrief.html
src/pages/debrief/debrief.ts
src/pages/waiting-room-to-car/components/eyesight-failure-confirmation/__tests__/eyesight-failure-confirmation.spec.ts
src/pages/waiting-room-to-car/components/eyesight-failure-confirmation/eyesight-failure-confirmation.html
src/pages/waiting-room-to-car/components/eyesight-failure-confirmation/eyesight-failure-confirmation.ts

* Create a handler for when the test termination is confirmed
* Update debrief nav params and template to display "terminated"

MES-984: Confirm test termination

---

src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/end-test-modal/__tests__/end-test-modal.spec.ts
src/pages/test-report/components/end-test-modal/end-test-modal.html
src/pages/test-report/components/end-test-modal/end-test-modal.module.ts
src/pages/test-report/components/end-test-modal/end-test-modal.scss
src/pages/test-report/components/end-test-modal/end-test-modal.ts
src/pages/test-report/components/test-report-components.module.ts
src/pages/test-report/test-report.ts
src/theme/sass-partials/_modal.scss

- Create an end test modal for when the legal requirements have been completed
- Add modal alert styling to sass partials for use by other modal alerts

MES-2198 create end test modal

---

src/modules/tests/test-data/__tests__/test-data.selector.spec.ts
src/modules/tests/test-data/test-data.models.ts
src/modules/tests/test-data/test-data.selector.ts
src/pages/journal/journal.effects.ts
src/pages/test-report/__tests__/test-report.effects.spec.ts
src/pages/test-report/__tests__/test-report.reducer.spec.ts
src/pages/test-report/__tests__/test-report.selector.spec.ts
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/competency/competency.constants.ts
src/pages/test-report/test-report.actions.ts
src/pages/test-report/test-report.effects.ts
src/pages/test-report/test-report.model.ts
src/pages/test-report/test-report.module.ts
src/pages/test-report/test-report.reducer.ts
src/pages/test-report/test-report.selector.ts
src/pages/test-report/test-report.ts
src/providers/test-report-validator/__mocks__/test-report-validator.mock.ts
src/providers/test-report-validator/__tests__/test-report-validator.spec.ts
src/providers/test-report-validator/test-report-validator.ts

- Adds Validator to check legal requirements have been met for a test
- Fixes one of the labels for Kaisa

MES-2170 - Test Report Validator Provider

---

mock/local-journal.json
src/pages/test-report/__tests__/test-report.effects.spec.ts
src/pages/test-report/__tests__/test-report.reducer.spec.ts
src/pages/test-report/__tests__/test-report.selector.spec.ts
src/pages/test-report/test-report.actions.ts
src/pages/test-report/test-report.effects.ts
src/pages/test-report/test-report.model.ts
src/pages/test-report/test-report.module.ts
src/pages/test-report/test-report.reducer.ts
src/pages/test-report/test-report.selector.ts
src/pages/test-report/test-report.ts
src/providers/test-result/__mocks__/test-result.mock.ts
src/providers/test-result/__tests__/test-result.spec.ts
src/providers/test-result/test-result.model.ts
src/providers/test-result/test-result.ts

This PR contains the basic framework needed to calculate a test result. It does not include:
- The calculation of the result
- Passing the result to the debrief page

Mes-89 Framework for Calculating a Test Result

---

src/pages/journal/components/test-outcome/test-outcome.ts
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/components/end-test-modal/__tests__/end-test-modal.spec.ts
src/pages/test-report/components/end-test-modal/end-test-modal.scss
src/pages/test-report/components/end-test-modal/end-test-modal.ts
src/pages/test-report/components/legal-requirements-modal/__tests__/legal-requirements-modal.spec.ts
src/pages/test-report/components/legal-requirements-modal/legal-requirements-modal.html
src/pages/test-report/components/legal-requirements-modal/legal-requirements-modal.module.ts
src/pages/test-report/components/legal-requirements-modal/legal-requirements-modal.scss
src/pages/test-report/components/legal-requirements-modal/legal-requirements-modal.ts
src/pages/test-report/components/test-report-components.module.ts
src/pages/test-report/test-report.constants.ts
src/pages/test-report/test-report.html
src/pages/test-report/test-report.ts
src/shared/constants/legal-requirements/catb-legal-requirements.ts
src/theme/sass-partials/_modal.scss

- Create modal for legal requirements
- Refactor modal styling (again) to make it consistent and more reusable

MES-2197 legal requirements validation modal

---

src/pages/journal/components/test-outcome/test-outcome.html
src/pages/journal/components/test-outcome/test-outcome.ts

- showResumeTestButton() added to test-outcome.ts to determine if the 'resume' button should be displayed
- Addition of the resume button template to test-outcome.html
- Default redirect added to WaitingRoomPage

Adding resume button

---

mock/local-journal.json
src/modules/tests/test-data/__tests__/test-data.selector.spec.ts
src/modules/tests/test-data/test-data.actions.ts
src/modules/tests/test-data/test-data.reducer.ts
src/modules/tests/test-data/test-data.selector.ts
src/pages/debrief/__tests__/debrief.spec.ts
src/pages/test-report/components/vehicle-check/__tests__/vehicle-check.spec.ts
src/pages/test-report/components/vehicle-check/vehicle-check.ts

- Record a dangerous fault against show me question
- Record a driving fault agains show me question
- Toggle show me question's completed status
- Remove show me question faults
- Update global fault counter

MES-1013 Vehicle Checks

---

src/modules/tests/test-data/test-data.actions.ts

Fixed SHOW_ME_QUESTION_CORRECT error

---

src/modules/tests/tests.reducer.ts

Fixed issue with activity code going walkabouts

---

src/providers/authentication/__tests__/authentication.spec.ts
src/providers/authentication/authentication.ts

fixes potential type error with employee id

---

src/modules/tests/test-data/test-data.actions.ts
src/pages/debrief/__tests__/debrief.spec.ts
src/pages/debrief/debrief.html
src/pages/debrief/debrief.selector.ts
src/pages/debrief/debrief.ts
src/pages/test-report/test-report.effects.ts
src/pages/test-report/test-report.ts
src/providers/test-result/__tests__/test-result.spec.ts
src/providers/test-result/test-result.ts

- Calculate the result of the test report
- Create a selector for the debrief page to make it apparent what the result is (pass, fail, terminated) rather than an activity code (1, 2...)

MES-2231 calculate test result

---

src/components/signature-area/signature-area.ts
src/pages/waiting-room/__tests__/waiting-room.spec.ts
src/pages/waiting-room/waiting-room.html
src/pages/waiting-room/waiting-room.ts

Rehydrating the checkboxes and signature if app crashed.
https://jira.i-env.net/browse/MES-2232

MES-2232 - Rehydrating WR page

---

src/pages/debrief/debrief.selector.ts
src/pages/test-report/__tests__/test-report.effects.spec.ts
src/pages/test-report/test-report.effects.ts
src/pages/test-report/test-report.html
src/pages/test-report/test-report.ts
src/providers/test-report-validator/__mocks__/test-report-validator.mock.ts
src/providers/test-report-validator/__tests__/test-report-validator.spec.ts
src/providers/test-report-validator/test-report-validator.ts
src/providers/test-result/__tests__/test-result.spec.ts
src/providers/test-result/test-result.ts

- Fixes issue with show me/tell me validation
- Fixes issue with calculating test results for tests which are not a standard fail
- Made Effects Safe Again
- Removed Pass Test & Fail Test Button

Validate test result refactor

---

src/pages/login/__tests__/login.spec.ts

Uses the secure storage mock in tests as it wasn't before and was creating a load of spam in the tests.

Use secure storage mock in tests

---

src/pages/health-declaration/__tests__/health-declaration.spec.ts
src/pages/health-declaration/health-declaration.html
src/pages/health-declaration/health-declaration.ts
src/pages/waiting-room/__tests__/waiting-room.spec.ts

May be redundant due to the in car part of the test being finished after the Health Declaration page.
This story is just to ensure the health declaration page data is rehydrated same as the other pages.
https://jira.i-env.net/browse/MES-2236

MES-2236 - Health Declaration Rehydration

---

src/pages/test-report/__tests__/test-report.effects.spec.ts
src/pages/test-report/test-report.effects.ts

- Saves the current state of the test every time an action is performed on the test report

Mes 2145 - Auto save data on test report

---

src/modules/tests/test-status/__tests__/test-status.reducer.spec.ts
src/modules/tests/test-status/test-status.actions.ts
src/modules/tests/test-status/test-status.model.ts
src/modules/tests/test-status/test-status.reducer.ts
src/pages/office/office.ts

- Allows the setting of the Test Status to Completed
- Allows the setting of the Test Status to Submitted
- Set the test status to be completed when we click the submit button on the office page

MES-1128 - Mark Test as Completed or Submitted

---

src/pages/login/__tests__/login.spec.ts
src/pages/login/login.html
src/pages/login/login.scss
src/pages/login/login.ts
src/providers/app-config/app-config.constants.ts
src/providers/app-config/app-config.ts

- Refactors app initialisation promise chain to use async/await
- Catches errors when trying to load config from mobile device management
- Adds an 'Show error details' link displaying the stringified error when the error is unknown
**Screenshots**
Show error details:
Error details modal:

Mes 2252 - App config initialisation refactor and error handling

---

src/pages/office/__tests__/office.spec.ts
src/pages/office/office.html
src/pages/office/office.scss
src/pages/office/office.ts

- Adds an alert at the end of the test which asks the DE to confirm they want to end it.

MES-2280 - Added confirmation modal when ending tests

---

src/modules/tests/test-data/test-data.selector.ts
src/modules/tests/tests.actions.ts
src/modules/tests/tests.module.ts
src/pages/test-report/components/competency-button/competency-button.ts
src/pages/test-report/components/timer/timer.ts
src/providers/test-submission/__mocks__/test-submission.mock.ts
src/providers/test-submission/__tests__/test-submission.spec.ts
src/providers/test-submission/test-submission.ts

The aim of this  PR is to create the basics allowing us to split the ticket easily across multiple people in the team.
- Creates a Test Submission Provider
- Creates actions which are required for the process

MES-1542 - Upload Submitted Tests - The Basics

---

src/pages/journal/components/practice-card/practice-card.html
src/pages/journal/components/practice-card/practice-card.scss
src/pages/journal/components/practice-test-modal/practice-test-modal.html
src/pages/journal/components/practice-test-modal/practice-test-modal.scss
src/pages/journal/journal.html

Change the wording on the card and modal used top access a practice test

Update the wording for accessing practice mode

---

src/pages/debrief/__tests__/debrief.spec.ts
src/pages/debrief/debrief.ts
src/pages/test-report/__tests__/test-report.spec.ts
src/pages/test-report/test-report.ts

- Enable Single App Mode, Insomnia and lock screen orientation when a practice test is started.
- Disable the plugins when the practice test is ended.

MES-2296 - enable plugins for practice mode

---

src/assets/i18n/cy.json
src/assets/i18n/en.json
src/components/candidate-section/candidate-section.html
src/components/components.module.ts
src/components/screen-lock-indicator/__tests__/screen-lock-indicator.spec.ts
src/components/screen-lock-indicator/lock-screen-indicator.html
src/components/signature-area/signature-area.ts
src/pages/waiting-room/waiting-room.html
src/pages/waiting-room/waiting-room.ts

* Extract i18n JSON keys for strings provided either in TypeScript or in sub-components

MES-2307: Waiting Room TypeScript + nested translations (MES-1886)

---

src/pages/debrief/debrief.html

Updated Copy on Debrief Page

---

src/pages/login/__tests__/login.spec.ts
src/pages/login/login.ts

- Fixes offline journal by awaiting on the initialisation of persistent storage.
- Adds unit tests coverage to the order of async operations in the `login()` method

Mes 2335 offline defect

---

src/pages/journal/__tests__/journal.effects.spec.ts
src/pages/journal/journal.effects.ts

This PR fixes a couple of TODO comments in the Journal Effects

Fix Todos in Journal Effects

---

src/assets/i18n/cy.json
src/assets/i18n/en.json
src/pages/debrief/__tests__/debrief.spec.ts
src/pages/debrief/debrief.html
src/pages/debrief/debrief.module.ts
src/pages/debrief/debrief.ts

* Extract strings from Debrief template to `en`/`cy` i18n JSON file

MES-1888: Debrief i18n

---

src/pages/back-to-office/back-to-office.html
src/pages/waiting-room-to-car/components/eyesight-test/eyesight-test.html
src/pages/waiting-room-to-car/components/tell-me-question-card/tell-me-question-card.html
src/pages/waiting-room-to-car/components/transmission/transmission.html
src/pages/waiting-room-to-car/components/vehicle-registration/vehicle-registration.html
src/pages/waiting-room-to-car/waiting-room-to-car.html
test/e2e/features/02-journal.feature
test/e2e/features/03-waitingroom.feature
test/e2e/features/04-waitingroomtocar.feature
test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/backtooffice-steps.ts
test/e2e/step-definitions/debrief-steps.ts
test/e2e/step-definitions/generic-steps.ts
test/e2e/step-definitions/healthdeclaration-steps.ts
test/e2e/step-definitions/office-steps.ts
test/e2e/step-definitions/testreport-steps.ts
test/e2e/step-definitions/waitingroom-steps.ts
test/e2e/step-definitions/waitingroomtocar-steps.ts

Adding a basic full end to end test journey as a basis for all other UI tests.
Also includes basic validation checks for Waiting room to car page

Addition of ui tests

---

src/providers/test-submission/__tests__/test-submission.spec.ts
src/providers/test-submission/test-submission.ts

- Compresses the Test Result Data and outputs as Base 64.

MES-1542 - Compress Test Result Data

---

.gitignore
README.md
package-lock.json
package.json
test/e2e/README.md

Updates for the UI Testsuite including
- Removing test.config.ts file from repository to prevent accidental commit
- Update to README.md for new procedure - uses appium in package.json rather than global
- Update version of appium in package.json

Ui automation framework changes

---

mock/local-journal.json
src/assets/i18n/cy.json
src/assets/i18n/en.json
src/pages/health-declaration/__tests__/health-declaration.spec.ts
src/pages/health-declaration/health-declaration.html
src/pages/health-declaration/health-declaration.module.ts
src/pages/health-declaration/health-declaration.ts

* Extract English Health Declaration strings to `en.json`, provide `cy.json` placeholders
* Set the language to `cy` for Welsh tests on the Health Declaration page
* Extract a reusable current test observable to remove duplication

MES-1889: Health declaration i18n

---

README.md
test/e2e/step-definitions/journal-steps.ts

Fixes broken UI test for Journal welsh test indicator.

Fixing broken UI test by updating welsh indicator location

---

package-lock.json
package.json

Updating mes-test-schema dependency

---

src/modules/tests/test-slot-attributes/__tests__/test-slot-attributes.selector.spec.ts
src/modules/tests/test-slot-attributes/test-slot-attributes.selector.ts
src/pages/debrief/debrief.ts
src/pages/health-declaration/health-declaration.ts
src/pages/waiting-room/waiting-room.ts

Last PR for this ticket (hopefully)
- Fixes selectors with TODO's aimed at this ticket
- Renames a couple of selectors which are booleans from get to is

MES-2336 - Fix Selector TODOs

---

src/environment/environment.local.ts
src/environment/models/environment.model.ts
src/pages/journal/__tests__/journal.spec.ts
src/pages/journal/journal.html
src/pages/journal/journal.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment-response.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts

- Added Practice Mode Toggles to the App Config
- Added Toggle for hiding the test report end to end mode

Mes 2337 - Added Practice Mode Toggles

---

src/pages/candidate-details/candidate-details.html

- Removed 'Call Deployment' text
- Fixed capitalisation in label

MES-2264 - Updated Entitlement Check Text

---

src/modules/tests/communication-preferences/communication-preferences.selector.ts
src/pages/communication-page/__tests__/communication.spec.ts
src/pages/communication-page/communication.html
src/pages/communication-page/communication.scss
src/pages/communication-page/communication.ts
src/pages/communication-page/components/new-email/new-email.html
src/pages/communication-page/components/new-email/new-email.ts
src/pages/communication-page/components/provided-email/provided-email.html
src/pages/communication-page/components/provided-email/provided-email.ts

- Rehydrate new email field.
- Initialise a default selection of provided email, if one is available.
- Initialise a default selection of new email, if a provided email is unavailable.

mes-1774: Rehydration of input field for new email

---

bin/update-mock-data.ts
mock/local-journal-non-test-activities.json

- Auto-update dates for the non-test activities mock data.
- Update non-test activities mock data to fit the type definitions in [DJournal.ts](https://github.com/dvsa/mes-mobile-app/blob/develop/src/shared/models/DJournal.ts)
- [] git branch contains relevant JIRA ticket number

Update non-test-activity mock data

---

src/pages/communication-page/components/new-email/new-email.html
src/pages/office/components/candidate-description/candidate-description.html
test/e2e/features/03-waitingroom.feature
test/e2e/features/04-waitingroomtocar.feature
test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/generic-steps.ts
test/e2e/step-definitions/office-steps.ts
test/e2e/step-definitions/waitingroom-steps.ts

Added a couple basic test termination scenarios.
Incorporates a fix to the UI tests following updates to the communications page email validation.

Addition of test termination scenarios

---

mock/local-journal-non-test-activities.json
mock/local-journal.json
src/modules/tests/__mocks__/tests.mock.ts
src/modules/tests/__tests__/tests.effects.spec.ts
src/modules/tests/__tests__/tests.reducer.spec.ts
src/modules/tests/__tests__/tests.selector.spec.ts
src/modules/tests/tests.actions.ts
src/modules/tests/tests.effects.ts
src/modules/tests/tests.reducer.ts
src/modules/tests/tests.selector.ts
src/pages/debrief/debrief.ts
src/pages/journal/components/practice-card/practice-card.ts
src/pages/test-report/test-report.effects.ts
src/pages/test-report/test-report.ts

- Adding test report practice mode mock data
- Adding end 2 end practice mode mock data
- Using the test report practice mode mock data at the relevant places

MES-1975: Introducing test report & end 2 end practice mode mock data

---

mock/local-journal-non-test-activities.json
mock/local-journal.json
src/pages/office/components/fault-comment-card/fault-comment-card.html
src/pages/office/components/fault-comment-card/fault-comment-card.ts
src/pages/office/components/fault-comment/__tests__/fault-comment.spec.ts
src/pages/office/components/fault-comment/fault-comment.ts
src/pages/office/office.html
src/pages/office/office.ts

MES 2393 
fix bug that was found during show and tell, and prevented uploading of tests due to validation issues.

Bug mes 2393 office write up page validation error

---

src/pages/journal/__tests__/journal.spec.ts
src/pages/journal/components/journal-components.module.ts
src/pages/journal/components/practice-end-to-end-card/__tests__/practice-end-to-end-card.spec.ts
src/pages/journal/components/practice-end-to-end-card/practice-end-to-end-card.html
src/pages/journal/components/practice-end-to-end-card/practice-end-to-end-card.scss
src/pages/journal/components/practice-end-to-end-card/practice-end-to-end-card.ts
src/pages/journal/components/practice-test-report-card/__tests__/practice-test-report-card.spec.ts
src/pages/journal/components/practice-test-report-card/practice-test-report-card.html
src/pages/journal/components/practice-test-report-card/practice-test-report-card.scss
src/pages/journal/components/practice-test-report-card/practice-test-report-card.ts
src/pages/journal/journal.html
src/pages/journal/journal.scss

- Renames and updates the Test Report Practice Mode card
- Adds the slot to practice an end to end (Kept as 2 components due to potential deviations in design for the end to end slot due to displaying candidate details)

Mes 1976 - Access end to end practice mode

---

mock/local-journal.json
src/pages/candidate-details/candidate-details.html
src/pages/candidate-details/candidate-details.model.ts
src/pages/candidate-details/candidate-details.selector.ts

Added meeting place to candidate details.
https://jira.i-env.net/browse/MES-2129

MES-2129 - Added meeting place to candidate details

---

package-lock.json
package.json

- Upgrades ionic-angular to the latest version

MES-2392 - Fix page scrolling on ios 12.2

---

mock/local-journal-non-test-activities.json
mock/local-journal.json
src/assets/i18n/cy.json
src/assets/i18n/en.json
src/pages/communication-page/__tests__/communication.spec.ts
src/pages/communication-page/communication.html
src/pages/communication-page/communication.module.ts
src/pages/communication-page/communication.ts
src/pages/communication-page/components/new-email/__tests__/new-email.spec.ts
src/pages/communication-page/components/new-email/new-email.html
src/pages/communication-page/components/new-email/new-email.ts
src/pages/communication-page/components/postal-address/__tests__/postal-address.spec.ts
src/pages/communication-page/components/postal-address/postal-address.html
src/pages/communication-page/components/provided-email/__tests__/provided-email.spec.ts
src/pages/communication-page/components/provided-email/provided-email.html

* i18n for top level comms capture page and all its sub-components
* Extract strings to both `en.json` and `cy.json` (placeholders)

MES-2300: Comms capture i18n

---

src/modules/tests/__tests__/tests.selector.spec.ts
src/modules/tests/tests.selector.ts
src/pages/back-to-office/back-to-office.ts
src/pages/communication-page/communication.ts
src/pages/debrief/debrief.ts
src/pages/health-declaration/health-declaration.ts
src/pages/office/office.ts
src/pages/pass-finalisation/pass-finalisation.ts
src/pages/test-report/test-report.ts
src/pages/waiting-room-to-car/waiting-room-to-car.ts
src/pages/waiting-room/waiting-room.ts
src/shared/classes/practiceable-base-page.ts

- Adds new selectors for checking if we are in practice mode
- Adds a new base page class for pages using practice mode
- Updates all test pages to use new base class

Mes-1980 - Adds ability to check for practice mode on all tests pages

---

src/pages/pass-finalisation/__tests__/pass-finalisation.spec.ts
src/pages/pass-finalisation/pass-finalisation.html
src/pages/pass-finalisation/pass-finalisation.ts

MES 2366 Add transmission question to the pass debrief page, so that examiners can change the setting if they set it wrong earlier in the journey.

Feature mes 2366 transmission question pass debrief

---

test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/office-steps.ts
test/e2e/step-definitions/testreport-steps.ts

Adding another full journey UI test covering a failure.
This adds functionality to select driver, serious and dangerous faults.
The selecting of faults uses a different technique as long press is required to activate a driver fault.

Adding simple failure scenario with various faults

---

src/pages/journal/components/journal-components.module.ts
src/pages/journal/components/progressive-access/__tests__/progressive-access.spec.ts
src/pages/journal/components/progressive-access/progressive-access.html
src/pages/journal/components/progressive-access/progressive-access.scss
src/pages/journal/components/progressive-access/progressive-access.ts
src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
src/pages/journal/components/test-slot/test-slot.html
src/pages/journal/components/test-slot/test-slot.scss

- created a `progressive-access` component that takes the application state value for `progressive-access` to conditionally render the component on `test-slot-footer`.

MES-2128: Adding progressive access files

---

package-lock.json
package.json
src/components/components.module.ts
src/components/conducted-language/conducted-language.html
src/components/conducted-language/conducted-language.scss
src/components/conducted-language/conducted-language.ts
src/modules/tests/communication-preferences/communication-preferences.actions.ts
src/modules/tests/communication-preferences/communication-preferences.reducer.ts
src/modules/tests/communication-preferences/communication-preferences.selector.ts
src/pages/communication-page/__tests__/communication.spec.ts
src/pages/communication-page/communication.html
src/pages/communication-page/communication.ts

- Added 'ConductedLanguageComponent' to display Welsh/English toggle on 'Communication Capture Page'
- Dispatch actions created to handle state management

Feature mes 2265 switch welsh test to english

---

src/components/components.module.ts
src/components/display-address/__tests__/display-address.spec.ts
src/components/display-address/display-address.html
src/components/display-address/display-address.ts
src/pages/candidate-details/__tests__/candidate-details.selector.spec.ts
src/pages/candidate-details/__tests__/candidate-details.spec.ts
src/pages/candidate-details/candidate-details.html
src/pages/candidate-details/candidate-details.model.ts
src/pages/candidate-details/candidate-details.module.ts
src/pages/candidate-details/candidate-details.selector.ts
src/pages/candidate-details/candidate-details.ts
src/pages/communication-page/components/postal-address/postal-address.html
src/pages/communication-page/components/postal-address/postal-address.scss

Added business details to candidate details page. 
Address component created to keep consistency,
https://jira.i-env.net/browse/MES-2130

MES-2130 - Business Details

---

bin/fetch-logs-api-key.sh
mock/local-journal-non-test-activities.json
mock/local-journal.json
src/environment/environment.dev.ts
src/environment/environment.local.ts
src/environment/environment.perf.ts
src/environment/environment.production.ts
src/environment/environment.staging.ts
src/environment/environment.uat.ts
src/environment/models/environment.model.ts
src/pages/journal/journal.html
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts

* Add `logsPostApiKey` to the `AppConfig` and `EnvironmentFile` types
* Provide blank placeholders for the API key in all env files
* Source the API key from MDM config
* Add a script to splice the API key for a given env into the `environment.ts`

MES-2432: Obtain API key via MDM config for unauthenticated logging

---

test/e2e/features/03-waitingroom.feature
test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/debrief-steps.ts
test/e2e/step-definitions/office-steps.ts
test/e2e/step-definitions/waitingroom-steps.ts
test/e2e/step-definitions/waitingroomtocar-steps.ts

Adding a full end to end journey to cover off Eyesight failures and adding in additional checks into waiting room and debrief screen.

Adding scenario for eye sight failure

---

src/pages/back-to-office/__tests__/back-to-office.spec.ts
src/pages/back-to-office/back-to-office.html
src/pages/back-to-office/back-to-office.ts
src/pages/debrief/__tests__/debrief.spec.ts
src/pages/debrief/debrief.ts
src/pages/office/__tests__/office.spec.ts
src/pages/office/office.ts
src/shared/classes/practiceable-base-page.ts

- Add's flags to the base page for type of practice test
- Updates Journal Navigation in Back to Office Page
- Updates Journal Navigation in Debrief Page
- Updates Journal Navigation in Office Page

MES-2425 Update navigation for practice mode

---

test/e2e/step-definitions/generic-steps.ts
test/e2e/step-definitions/testreport-steps.ts

A couple tweaks to try to improve stability of UI tests.

Update to reset app state step

---

src/modules/tests/__mocks__/tests.mock.ts
src/modules/tests/__tests__/tests.reducer.spec.ts
src/modules/tests/__tests__/tests.selector.spec.ts
src/modules/tests/tests.effects.ts
src/modules/tests/tests.reducer.ts
src/modules/tests/tests.selector.ts
src/pages/fake-journal/__mocks__/fake-journal.mock.ts
src/pages/fake-journal/fake-journal.ts
src/shared/mocks/test-slot-ids.mock.ts

- Declaring the testReport & end2end test ids
- Using the ids wherever they are needed

MES-2440: Defining the Ids for fake journal slots

---

src/pages/fake-candidate-details/__tests__/fake-candidate-details.spec.ts
src/pages/fake-candidate-details/fake-candidate-details.html
src/pages/fake-candidate-details/fake-candidate-details.module.ts
src/pages/fake-candidate-details/fake-candidate-details.scss
src/pages/fake-candidate-details/fake-candidate-details.ts
src/pages/journal/components/candidate-link/__tests__/candidate-link.spec.ts
src/pages/journal/components/candidate-link/candidate-link.ts

- Adds a new page FakeCandidateDetails
- Adds logic to decide which candidate details to open based on the slot id

MES-1977 - Fake Candidate Details Page

---

src/pages/fake-candidate-details/__tests__/fake-candidate-details.spec.ts
src/pages/fake-candidate-details/fake-candidate-details.html
src/pages/fake-candidate-details/fake-candidate-details.ts

- Populates the FakeCandidateDetails Page with fake candidate details

Mes-1977 - Complete fake candidate details page

---

src/modules/tests/tests.effects.ts

MES-1978 - Prevents test persistence when in practice mode

---

src/modules/tests/tests.reducer.ts
src/pages/back-to-office/__tests__/back-to-office.spec.ts
src/pages/back-to-office/back-to-office.ts
src/pages/fake-journal/fake-journal.ts
src/pages/office/__tests__/office.spec.ts
src/pages/office/office.ts

- Reset the state of the Practice Test when we start a new one.
- Fix Navigation Issues

MES-1977 - Reset Practice Test Data

---

package-lock.json
package.json
src/modules/tests/__tests__/tests.selector.spec.ts
src/modules/tests/test-centre/__tests__/test-centre.reducer.spec.ts
src/modules/tests/test-centre/__tests__/test-centre.selector.spec.ts
src/modules/tests/test-centre/test-centre.reducer.ts
src/pages/fake-journal/fake-journal.effects.ts
src/pages/journal/journal.effects.ts

* Adopts `@dvsa/mes-test-schema@1.0.16` (https://github.com/dvsa/mes-api-definitions/pull/33)
* Copy the test centre ID from the journal into the test state

MES-2295: Track test centre ID in test state

---

src/components/conducted-language/conducted-language.html
src/components/conducted-language/conducted-language.scss

- Current selected language should not have link styling

MES-2265: Fixing inactive link

---

test/e2e/features/02-journal.feature
test/e2e/features/03-waitingroom.feature
test/e2e/features/04-waitingroomtocar.feature
test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/generic-steps.ts
test/e2e/step-definitions/journal-steps.ts
test/e2e/step-definitions/testreport-steps.ts
test/e2e/step-definitions/waitingroomtocar-steps.ts

- Added tell me question UI checks.
- Added Driver fault count UI checks.
- Updated step definitions to be smarter when performing application resets. Now only resets the device state when necessary and updated to make better use of the test data.

Addition of driver fault count checking

---

src/pages/journal/journal.effects.ts

* Relates to https://jira.i-env.net/browse/MES-2295
* `staffNumber` needs to be included in the submission payload to be saved into the Aurora record
* Ensure that we populate it when starting a test
* **Needs confirmation of behaviour when we start a test while in unauthenticated mode**

Ensure that examiner staff number is copied into test state to make test submission valid

---

test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/generic-steps.ts

Some performance improvements and a fix to a UI test.

Ui test performance improvements

---

src/pages/back-to-office/back-to-office.ts
src/pages/office/components/activity-code/activity-code.html
src/pages/office/office.ts
src/shared/classes/practiceable-base-page.ts

- Fixes Navigation Issue in Practice Mode - Thanks @szabolcs-keresztes 
- Fixes typo in Activity Code

Show and tell fixes

---

src/pages/candidate-details/__tests__/candidate-details.selector.spec.ts
src/pages/candidate-details/candidate-details.html
src/pages/candidate-details/candidate-details.selector.ts
src/pages/candidate-details/candidate-details.ts
src/pages/fake-candidate-details/fake-candidate-details.html
src/pages/fake-journal/__mocks__/fake-journal.mock.ts
src/pages/fake-journal/components/fake-test-slot/fake-test-slot.ts
src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
src/pages/journal/components/test-slot/test-slot.ts
src/shared/models/slot-types.ts

- Removes magic strings in the slot type calculations
- Shows Indicator when slot is not STANDARD_TEST
- Changes Fake Journal Test Slots to be Standard Tests

MES-2482 - Show Indictor on Slot when not Standard Test

---

config.xml
fastlane/Fastfile

Updates to new app bundle id

---

src/environment/environment.dev.ts
src/environment/environment.local.ts
src/environment/environment.perf.ts
src/environment/environment.uat.ts

updates bundle id for AAD

---

src/pages/fake-candidate-details/fake-candidate-details.html

- Fixes bug with showing the slot type indicator on the fake candidate details page

Fixed Issue with Slot Type Indicator

---

src/pages/fake-journal/__mocks__/fake-journal.mock.ts

- Fixes issues with the slots not being standard on the fake journal

Fix data issues on Fake Journal

---

README.md

Add docs about logs API fetching script

---

buildScripts/rename-artifact.js
config.xml
e2e-simulator-bdd.conf.js
fastlane/Fastfile

Updating name to remove spaces as this breaks the build.

Updating fastfile for name change

---

e2e-simulator-bdd.conf.js
src/pages/health-declaration/health-declaration.html
test/e2e/features/06-debrief.feature
test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/generic-steps.ts
test/e2e/step-definitions/healthdeclaration-steps.ts
test/e2e/step-definitions/waitingroom-steps.ts

Adding basic health declaration page checks and adding variations for comms capture page.
Also added fail fast on UI tests to speed up build outcome.

Mes 2176 ui tests health declaration

---

src/modules/tests/pass-completion/__tests__/pass-completion.reducer.spec.ts
src/modules/tests/pass-completion/pass-completion.reducer.ts

* Fixes broken UI test introduced by #504

Default to unanswered for Provisional Licence Provided

---

src/pages/office/components/d255/d255.html
src/pages/office/components/debrief-witnessed/debrief-witnessed.html
src/pages/office/components/independent-driving/independent-driving.html
src/pages/office/components/route-number/route-number.html
src/pages/office/components/show-me-question/show-me-question.html
src/pages/office/components/weather-conditions/weather-conditions.html
src/pages/office/office.html
test/e2e/features/07-office.feature
test/e2e/step-definitions/office-steps.ts
test/e2e/step-definitions/waitingroomtocar-steps.ts

Adding basic office data and validation UI tests.

Mes 2177 adding office ui tests

---

package-lock.json
src/environment/environment.dev.ts
src/environment/environment.local.ts
src/environment/environment.perf.ts
src/environment/environment.production.ts
src/environment/environment.staging.ts
src/environment/environment.uat.ts
src/pages/journal/__tests__/journal.selector.spec.ts
src/pages/journal/components/journal-navigation/__tests__/journal-navigation.spec.ts
src/pages/journal/journal.selector.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/shared/helpers/date-time.ts

- Allow date traversal in the journal of up to 2 weeks.
- Extend caching period.

WIP: DES-2549: Extend journal look-back by 2 weeks

---

mock/local-journal-non-test-activities.json
mock/local-journal.json
src/pages/journal/components/journal-components.module.ts
src/pages/journal/components/test-results-search-card/__tests__/test-results-search-card.spec.ts
src/pages/journal/components/test-results-search-card/test-results-search-card.html
src/pages/journal/components/test-results-search-card/test-results-search-card.scss
src/pages/journal/components/test-results-search-card/test-results-search-card.ts
src/pages/journal/journal.html
src/pages/journal/journal.scss
src/pages/test-results-search/__tests__/test-results-search.spec.ts
src/pages/test-results-search/test-results-search.html
src/pages/test-results-search/test-results-search.module.ts
src/pages/test-results-search/test-results-search.scss
src/pages/test-results-search/test-results-search.ts

MES-2637: Implementing search card and search page

---

test/e2e/extended/cat-b-scenarios.feature
test/e2e/features/06-debrief.feature
test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/debrief-steps.ts
test/e2e/step-definitions/office-steps.ts

Based on feedback adding extra UI page checks on office page.

Mes 2179 additional checks

---

package-lock.json
package.json
src/providers/search/__mocks__/search-results.mock.ts
src/providers/search/__mocks__/search.mock.ts
src/providers/search/__tests__/search.spec.ts
src/providers/search/search.ts
src/providers/url/url.ts

- Adds a search provider to the app so we can call the search endpoint

MES-2250 Search Provider

---

package-lock.json
package.json
src/providers/search/__mocks__/search-results.mock.ts

MES-2550 - Updated Schema Version

---

src/providers/search/__mocks__/search.mock.ts
src/providers/search/__tests__/search.spec.ts
src/providers/search/search.models.ts
src/providers/search/search.ts

- Added advanced search
- Updated other search functions with isLDTM flag

MES-2543 - Advanced Search Provider

---

mock/local-journal-non-test-activities.json
mock/local-journal.json
src/pages/test-results-search/__tests__/test-results-search.spec.ts
src/pages/test-results-search/test-results-search.module.ts
src/pages/test-results-search/test-results-search.ts
src/providers/search/search.ts

Use Candidate details search to make a DB query.
Logging out the array.

Hook up provider and ui

---

src/pages/journal/__tests__/journal.selector.spec.ts
src/providers/incomplete-tests/incomplete-tests.spec.ts

- Test improvements for navigating to next day

Feature des 2549 refactor test for navigation

---

src/pages/candidate-details/candidate-details.selector.ts

Fixed App Ref Display on Candidate Details

---

src/pages/test-results-search/test-results-search.html
src/pages/test-results-search/test-results-search.scss
src/pages/test-results-search/test-results-search.ts

- Adds bubbles spinner to search button
- Disables search button while spinner is active

MES-2832 - Search spinner

---

src/pages/journal/components/test-outcome/test-outcome.ts
src/pages/journal/journal-rekey-modal/journal-rekey-modal.module.ts

- Importing `TestReportModalModule` to avail of `modal-alert-title`
- Removing call to display modal until implementation is complete

MES-2547: Adding appropriate module and removing call to modal

---

config.xml
src/pages/journal/components/test-results-search-card/test-results-search-card.ts
src/pages/test-results-search/components/advanced-search/advanced-search.html
src/pages/test-results-search/components/advanced-search/advanced-search.scss
src/pages/test-results-search/components/advanced-search/advanced-search.ts
src/pages/test-results-search/components/test-results-search-components.module.ts
src/pages/test-results-search/test-results-search.html
src/pages/test-results-search/test-results-search.ts
src/providers/incomplete-tests/incomplete-tests.spec.ts
src/providers/incomplete-tests/incomplete-tests.ts
src/providers/search/__tests__/search.spec.ts
src/providers/search/search.ts

Implementing Advance search UI
Linking it with Provider
Linking results to Results list
Loading Spinner on button

MES-2836: Advanced Search

---

src/modules/tests/__tests__/tests.selector.spec.ts
src/modules/tests/tests.constants.ts
src/modules/tests/tests.selector.ts
src/pages/office/office.ts

- Removed the css class selector
- Removed some temporary code and tidied up the test result

Refactoring

---

src/app/__mocks__/app.component.mock.ts
src/pages/journal/components/candidate-link/__tests__/candidate-link.spec.ts
src/pages/page-names.constants.ts
src/pages/test-results-search/components/search-result/__tests__/search-result.spec.ts
src/pages/test-results-search/components/search-result/search-result.html
src/pages/test-results-search/components/search-result/search-result.ts
src/pages/view-test-result/__tests__/view-test-result.spec.ts
src/pages/view-test-result/view-test-result.html
src/pages/view-test-result/view-test-result.module.ts
src/pages/view-test-result/view-test-result.scss
src/pages/view-test-result/view-test-result.ts

- Adds new page View Test Result
- Open new page in Modal by clicking on search result
Next PR will make API call and display data

MES-1136 - View a completed test (Framework)

---

src/pages/journal/components/test-outcome/test-outcome.ts

Modal already closed here: https://github.com/dvsa/mes-mobile-app/blob/develop/src/pages/journal/journal-rekey-modal/journal-rekey-modal.ts#L17
Remove second close attempt.

Fix close re-key modal

---

package-lock.json

Updated package file to fix build

---

src/modules/tests/__tests__/tests.selector.spec.ts
src/modules/tests/tests.selector.ts
src/pages/fake-journal/components/fake-test-slot/fake-test-slot.html
src/pages/fake-journal/components/fake-test-slot/fake-test-slot.ts
src/pages/fake-journal/fake-journal.html
src/pages/journal/components/test-outcome/__tests__/test-outcome.spec.ts
src/pages/journal/components/test-outcome/test-outcome.html
src/pages/journal/components/test-outcome/test-outcome.ts
src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
src/pages/journal/components/test-slot/test-slot.html
src/pages/journal/components/test-slot/test-slot.ts

- Used protected type `SlotDetail` instead of `any` for `test-outcome` component
- Pulled through the test data into the `test-outcome` component using the `tests-selector`
- `ngIf` on whether the test is `Completed` or `Submitted` to display the activity code
https://jira.i-env.net/browse/MES-992

MES-992 - Show Outcome Code in Journal

---

test/e2e/features/02-journal.feature
test/e2e/features/03-waitingroom.feature
test/e2e/features/06-debrief.feature
test/e2e/step-definitions/testreport-steps.ts

Updates to improve stability around legal requirements completion and removal and consolidation of checks that are already covered under different tests.

Stability improvements remove redundant tests

---

src/modules/tests/tests.analytics.effects.ts
src/modules/tests/tests.module.ts
src/modules/tests/tests.selector.ts
src/pages/back-to-office/back-to-office.actions.ts
src/pages/back-to-office/back-to-office.analytics.effects.ts
src/pages/back-to-office/back-to-office.ts
src/pages/debrief/debrief.actions.ts
src/pages/debrief/debrief.analytics.effects.ts
src/pages/debrief/debrief.ts
src/pages/journal/components/test-outcome/test-outcome.ts
src/pages/journal/journal.actions.ts
src/pages/journal/journal.analytics.effects.ts
src/pages/office/__mocks__/toast-controller-mock.ts
src/pages/office/__tests__/office.spec.ts
src/pages/office/office.actions.ts
src/pages/office/office.analytics.effects.ts
src/pages/office/office.ts
src/providers/analytics/analytics.model.ts

MES-1982: Post-test Analytics

---

src/pages/back-to-office/back-to-office.analytics.effects.ts
test/e2e/extended/cat-b-scenarios.feature
test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/journal-steps.ts

Updating existing tests to also check the test result is correctly set on the journal page following test upload.
Added a couple basic rekey scenarios.

Mes 992 update ui tests to check result

---

src/pages/office/components/identification/identification.html
src/pages/pass-finalisation/pass-finalisation.html

MES-2491 - Fixed labels

---

src/pages/view-test-result/__tests__/view-test-result.spec.ts
src/pages/view-test-result/components/test-summary-card/__tests__/test-summary-card.spec.ts
src/pages/view-test-result/components/test-summary-card/test-summary-card-model.ts
src/pages/view-test-result/components/test-summary-card/test-summary-card.html
src/pages/view-test-result/components/test-summary-card/test-summary-card.scss
src/pages/view-test-result/components/test-summary-card/test-summary-card.ts
src/pages/view-test-result/components/view-test-result.components.module.ts
src/pages/view-test-result/view-test-result.html
src/pages/view-test-result/view-test-result.ts
src/shared/mocks/cat-b-test-result.mock.ts

- Adds a test summary card to the View Test Result Page

MES-1136 - Test Summary Card

---

src/pages/view-test-result/__tests__/view-test-result.spec.ts
src/pages/view-test-result/components/view-test-header/__tests__/view-test-header.spec.ts
src/pages/view-test-result/components/view-test-header/view-test-header.html
src/pages/view-test-result/components/view-test-header/view-test-header.model.ts
src/pages/view-test-result/components/view-test-header/view-test-header.scss
src/pages/view-test-result/components/view-test-header/view-test-header.ts
src/pages/view-test-result/components/view-test-result.components.module.ts
src/pages/view-test-result/view-test-result.html
src/pages/view-test-result/view-test-result.ts
src/shared/mocks/cat-b-test-result.mock.ts

- Added  ViewTestHeader component

Added Header Component for ViewTestResult page

---

src/environment/environment.local.ts
src/environment/models/environment.model.ts
src/pages/journal/components/test-slot/__tests__/test-slot.spec.ts
src/pages/journal/components/test-slot/test-slot.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts

* Extend the configuration model with `testPermissionPeriods` obtained from config service
* Assess the `testPermissionPeriods` for whether a particular test category can be started

MES-2816: Use test permission periods to determine whether tests can be started

---

src/pages/debrief/debrief.selector.ts
src/pages/view-test-result/__tests__/view-test-result.spec.ts
src/pages/view-test-result/components/debrief-card/__tests__/debrief-card.spec.ts
src/pages/view-test-result/components/debrief-card/debrief-card.html
src/pages/view-test-result/components/debrief-card/debrief-card.model.ts
src/pages/view-test-result/components/debrief-card/debrief-card.scss
src/pages/view-test-result/view-test-result.ts
src/shared/mocks/cat-b-test-result.mock.ts

- Added ability to view faults on View Result Page
- Associated tests
- Added a TODO in the Debrief selectors to refactor them out at a later date as they are now common (too much risk to do it this close to end of sprint)

MES-1136 - Show faults on View Result Page

---

src/pages/test-report/__tests__/test-report.analytics.effects.spec.ts
src/pages/test-report/__tests__/test-report.effects.spec.ts
src/pages/test-report/test-report.actions.ts
src/pages/test-report/test-report.analytics.effects.ts
src/pages/test-report/test-report.effects.ts
src/pages/test-report/test-report.ts
src/providers/analytics/analytics.model.ts

Add analytics event for test termination from the test report page.

MES-1622: Analytics test termination

---

src/environment/environment.local.ts
src/environment/models/environment.model.ts
src/pages/journal/components/test-slot/test-slot.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts
src/providers/app-config/constants/examiner-role.constants.ts

- Adding examiner role to config for future stories to conditionally show different journeys

Adding role to config

---

src/pages/test-results-search/__tests__/test-results-search.spec.ts
src/pages/test-results-search/components/advanced-search/advanced-search.html
src/pages/test-results-search/test-results-search.html
src/pages/test-results-search/test-results-search.scss
src/pages/test-results-search/test-results-search.ts

Performance issue when loading more than 30 test results has been solved.

MES-2920: Performance Issue Search Results

---

src/pages/view-test-result/components/debrief-card/debrief-card.html
src/pages/view-test-result/components/debrief-card/debrief-card.scss
src/pages/view-test-result/components/debrief-card/debrief-card.ts
src/pages/view-test-result/components/test-summary-card/test-summary-card.html

- Fixes a number of issues found by test
- Makes changes based on PO discussions
- Updates by UX

MES-1136 - UX tweaks

---

src/pages/view-test-result/components/debrief-card/debrief-card.html
src/pages/view-test-result/components/test-summary-card/test-summary-card.html
src/pages/view-test-result/view-test-result.scss

- Fix a number of issues with no data after seeking clarifications from the PO's
- Fix alignment issues introduced to develop (my bad)

MES-1136- PO Review Changes

---

src/assets/i18n/cy.json
src/assets/i18n/en.json
src/pages/communication-page/__tests__/communication.spec.ts
src/pages/communication-page/communication.html
src/pages/communication-page/communication.module.ts
src/pages/communication-page/communication.scss
src/pages/communication-page/components/privacy-notice/__tests__/privacy-notice.spec.ts
src/pages/communication-page/components/privacy-notice/privacy-notice.html
src/pages/communication-page/components/privacy-notice/privacy-notice.scss
src/pages/communication-page/components/privacy-notice/privacy-notice.ts
src/pages/test-results-search/components/search-result/search-result.html
src/pages/test-results-search/components/search-result/search-result.scss

- Added privacy notice component 
- Fixed issue with styling on search result (as @buzzub solved my issue with displaying the left hand bars

Added Privacy Notice

---

package-lock.json
package.json

Updating mes-test-schema

---

src/pages/test-results-search/__tests__/test-results-search.analytics.effects.spec.ts
src/pages/test-results-search/test-results-search.actions.ts
src/pages/test-results-search/test-results-search.analytics.effects.ts
src/pages/test-results-search/test-results-search.module.ts
src/pages/test-results-search/test-results-search.ts
src/providers/analytics/analytics.model.ts

- Adds a View Test Result Search Analytics Event
- Adds a Application Ref Search Analytics Event
- Adds a Driver Number Search Analytics Event
- Adds a LDTM Search Analytics Event
All Events Approved by Pam
Also added a couple of TODO's where we don't unsubscribe correctly

MES-1399 - Search Audit Events

---

src/pages/office/components/fault-comment/fault-comment.ts

Correcting the bug which was introduced by setting a validation criteria and removing the existing one.

Adding validation criteria as array

---

src/environment/environment.local.ts
src/environment/models/environment.model.ts
src/pages/journal/journal.effects.ts
src/pages/test-results-search/test-results-search.ts
src/pages/view-test-result/view-test-result.ts
src/providers/app-config/__mocks__/app-config.mock.ts
src/providers/app-config/__mocks__/environment.mock.ts
src/providers/app-config/app-config.model.ts
src/providers/app-config/app-config.ts
src/providers/journal/journal.ts
src/providers/search/__tests__/search.spec.ts
src/providers/search/search.ts

JIRA: https://jira.i-env.net/browse/MES-2493
Description: Now timeouts the request based on the configuration set, timed out requests are the journal, search results and get test result.

Mes 2493 timeout when backend unavailable

---

src/pages/view-test-result/__tests__/view-test-results.analytics.effects.spec.ts
src/pages/view-test-result/view-test-result.actions.ts
src/pages/view-test-result/view-test-result.analytics.effects.ts
src/pages/view-test-result/view-test-result.module.ts
src/pages/view-test-result/view-test-result.ts
src/providers/analytics/analytics.model.ts

- Added new Analytics event for entering the View Test Result Page

MES-1399 - View Test Result Audit Event

---

src/assets/i18n/cy.json
src/assets/i18n/en.json
src/modules/tests/communication-preferences/communication-preferences.actions.ts
src/modules/tests/communication-preferences/communication-preferences.reducer.ts
src/pages/communication-page/__tests__/communication.spec.ts
src/pages/communication-page/communication.html
src/pages/communication-page/communication.ts
test/e2e/features/99-fulljourney.feature
test/e2e/step-definitions/waitingroom-steps.ts

Removed all code relating to the `Support Centre` option on the communication page.
https://jira.i-env.net/browse/MES-2971

MES-2971 - Removed Support Centre Communication Radio

---

src/providers/app-config/app-config.ts

Now times out when app fails to get initial config on launch, uses cached config instead now.

Timeout when app initializing failing to call server

---

src/modules/tests/tests.actions.ts
src/modules/tests/tests.analytics.effects.ts
src/pages/test-report/test-report.effects.ts

Adding a label to outcome changed analytics event

Mes 3055 outcome changed event label

---

src/modules/tests/__tests__/tests.effects.analytics.spec.ts

Fixing the test outcome changed effects unit test

fixing a broken test

---

src/modules/tests/application-reference/__tests__/application-reference-selector.spec.ts
src/modules/tests/application-reference/application-reference.selector.ts
src/pages/candidate-details/candidate-details.selector.ts

The mobile app part of this ticket -> https://jira.i-env.net/browse/MES-2954
Have referenced the shared function `getApplicationNumber` to format the `applicationReference` correctly.

MES-2954 - Use application reference shared function

---

test/e2e/features/06-debrief.feature
test/e2e/features/99-fulljourney.feature

Fixing UI tests for MES-2994 and MES-2954

Mes 2994 e2e fix for eyesight test
